/*
 * This file is generated by jOOQ.
 */
package uk.ncl.giacomobergami.utils.database.jooq.tables.records;


import org.jooq.impl.TableRecordImpl;

import uk.ncl.giacomobergami.utils.database.jooq.tables.AccuratebatteryinfoImport;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AccuratebatteryinfoImportRecord extends TableRecordImpl<AccuratebatteryinfoImportRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.accuratebatteryinfo_import.iotdevicename</code>.
     */
    public void setIotdevicename(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.accuratebatteryinfo_import.iotdevicename</code>.
     */
    public String getIotdevicename() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.accuratebatteryinfo_import.consumption</code>.
     */
    public void setConsumption(Double value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.accuratebatteryinfo_import.consumption</code>.
     */
    public Double getConsumption() {
        return (Double) get(1);
    }

    /**
     * Setter for <code>public.accuratebatteryinfo_import.flowid</code>.
     */
    public void setFlowid(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.accuratebatteryinfo_import.flowid</code>.
     */
    public Integer getFlowid() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.accuratebatteryinfo_import.nopackets</code>.
     */
    public void setNopackets(Double value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.accuratebatteryinfo_import.nopackets</code>.
     */
    public Double getNopackets() {
        return (Double) get(3);
    }

    /**
     * Setter for <code>public.accuratebatteryinfo_import.time</code>.
     */
    public void setTime(Double value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.accuratebatteryinfo_import.time</code>.
     */
    public Double getTime() {
        return (Double) get(4);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AccuratebatteryinfoImportRecord
     */
    public AccuratebatteryinfoImportRecord() {
        super(AccuratebatteryinfoImport.ACCURATEBATTERYINFO_IMPORT);
    }

    /**
     * Create a detached, initialised AccuratebatteryinfoImportRecord
     */
    public AccuratebatteryinfoImportRecord(String iotdevicename, Double consumption, Integer flowid, Double nopackets, Double time) {
        super(AccuratebatteryinfoImport.ACCURATEBATTERYINFO_IMPORT);

        setIotdevicename(iotdevicename);
        setConsumption(consumption);
        setFlowid(flowid);
        setNopackets(nopackets);
        setTime(time);
        resetChangedOnNotNull();
    }
}
