/*
 * This file is generated by jOOQ.
 */
package uk.ncl.giacomobergami.utils.database.jooq.tables.records;


import org.jooq.impl.TableRecordImpl;

import uk.ncl.giacomobergami.utils.database.jooq.tables.AmbulanceinformationImport;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AmbulanceinformationImportRecord extends TableRecordImpl<AmbulanceinformationImportRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.ambulanceinformation_import.vehicle_id</code>.
     */
    public void setVehicleId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.ambulanceinformation_import.vehicle_id</code>.
     */
    public String getVehicleId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.ambulanceinformation_import.x</code>.
     */
    public void setX(Double value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.ambulanceinformation_import.x</code>.
     */
    public Double getX() {
        return (Double) get(1);
    }

    /**
     * Setter for <code>public.ambulanceinformation_import.y</code>.
     */
    public void setY(Double value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.ambulanceinformation_import.y</code>.
     */
    public Double getY() {
        return (Double) get(2);
    }

    /**
     * Setter for <code>public.ambulanceinformation_import.angle</code>.
     */
    public void setAngle(Double value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.ambulanceinformation_import.angle</code>.
     */
    public Double getAngle() {
        return (Double) get(3);
    }

    /**
     * Setter for <code>public.ambulanceinformation_import.vehicle_type</code>.
     */
    public void setVehicleType(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.ambulanceinformation_import.vehicle_type</code>.
     */
    public String getVehicleType() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.ambulanceinformation_import.speed</code>.
     */
    public void setSpeed(Double value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.ambulanceinformation_import.speed</code>.
     */
    public Double getSpeed() {
        return (Double) get(5);
    }

    /**
     * Setter for <code>public.ambulanceinformation_import.pos</code>.
     */
    public void setPos(Double value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.ambulanceinformation_import.pos</code>.
     */
    public Double getPos() {
        return (Double) get(6);
    }

    /**
     * Setter for <code>public.ambulanceinformation_import.lane</code>.
     */
    public void setLane(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.ambulanceinformation_import.lane</code>.
     */
    public String getLane() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.ambulanceinformation_import.slope</code>.
     */
    public void setSlope(Double value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.ambulanceinformation_import.slope</code>.
     */
    public Double getSlope() {
        return (Double) get(8);
    }

    /**
     * Setter for <code>public.ambulanceinformation_import.simtime</code>.
     */
    public void setSimtime(Double value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.ambulanceinformation_import.simtime</code>.
     */
    public Double getSimtime() {
        return (Double) get(9);
    }

    /**
     * Setter for <code>public.ambulanceinformation_import.injected</code>.
     */
    public void setInjected(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.ambulanceinformation_import.injected</code>.
     */
    public String getInjected() {
        return (String) get(10);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AmbulanceinformationImportRecord
     */
    public AmbulanceinformationImportRecord() {
        super(AmbulanceinformationImport.AMBULANCEINFORMATION_IMPORT);
    }

    /**
     * Create a detached, initialised AmbulanceinformationImportRecord
     */
    public AmbulanceinformationImportRecord(String vehicleId, Double x, Double y, Double angle, String vehicleType, Double speed, Double pos, String lane, Double slope, Double simtime, String injected) {
        super(AmbulanceinformationImport.AMBULANCEINFORMATION_IMPORT);

        setVehicleId(vehicleId);
        setX(x);
        setY(y);
        setAngle(angle);
        setVehicleType(vehicleType);
        setSpeed(speed);
        setPos(pos);
        setLane(lane);
        setSlope(slope);
        setSimtime(simtime);
        setInjected(injected);
        resetChangedOnNotNull();
    }
}
