/*
 * This file is generated by jOOQ.
 */
package uk.ncl.giacomobergami.utils.database.jooq.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import uk.ncl.giacomobergami.utils.database.jooq.tables.Ambulanceinformation;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AmbulanceinformationRecord extends UpdatableRecordImpl<AmbulanceinformationRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.ambulanceinformation.di_entry_id</code>.
     */
    public void setDiEntryId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.ambulanceinformation.di_entry_id</code>.
     */
    public Integer getDiEntryId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.ambulanceinformation.vehicle_id</code>.
     */
    public void setVehicleId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.ambulanceinformation.vehicle_id</code>.
     */
    public String getVehicleId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.ambulanceinformation.x</code>.
     */
    public void setX(Double value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.ambulanceinformation.x</code>.
     */
    public Double getX() {
        return (Double) get(2);
    }

    /**
     * Setter for <code>public.ambulanceinformation.y</code>.
     */
    public void setY(Double value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.ambulanceinformation.y</code>.
     */
    public Double getY() {
        return (Double) get(3);
    }

    /**
     * Setter for <code>public.ambulanceinformation.angle</code>.
     */
    public void setAngle(Double value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.ambulanceinformation.angle</code>.
     */
    public Double getAngle() {
        return (Double) get(4);
    }

    /**
     * Setter for <code>public.ambulanceinformation.vehicle_type</code>.
     */
    public void setVehicleType(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.ambulanceinformation.vehicle_type</code>.
     */
    public String getVehicleType() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.ambulanceinformation.speed</code>.
     */
    public void setSpeed(Double value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.ambulanceinformation.speed</code>.
     */
    public Double getSpeed() {
        return (Double) get(6);
    }

    /**
     * Setter for <code>public.ambulanceinformation.pos</code>.
     */
    public void setPos(Double value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.ambulanceinformation.pos</code>.
     */
    public Double getPos() {
        return (Double) get(7);
    }

    /**
     * Setter for <code>public.ambulanceinformation.lane</code>.
     */
    public void setLane(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.ambulanceinformation.lane</code>.
     */
    public String getLane() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.ambulanceinformation.slope</code>.
     */
    public void setSlope(Double value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.ambulanceinformation.slope</code>.
     */
    public Double getSlope() {
        return (Double) get(9);
    }

    /**
     * Setter for <code>public.ambulanceinformation.simtime</code>.
     */
    public void setSimtime(Double value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.ambulanceinformation.simtime</code>.
     */
    public Double getSimtime() {
        return (Double) get(10);
    }

    /**
     * Setter for <code>public.ambulanceinformation.injected</code>.
     */
    public void setInjected(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.ambulanceinformation.injected</code>.
     */
    public String getInjected() {
        return (String) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AmbulanceinformationRecord
     */
    public AmbulanceinformationRecord() {
        super(Ambulanceinformation.AMBULANCEINFORMATION);
    }

    /**
     * Create a detached, initialised AmbulanceinformationRecord
     */
    public AmbulanceinformationRecord(Integer diEntryId, String vehicleId, Double x, Double y, Double angle, String vehicleType, Double speed, Double pos, String lane, Double slope, Double simtime, String injected) {
        super(Ambulanceinformation.AMBULANCEINFORMATION);

        setDiEntryId(diEntryId);
        setVehicleId(vehicleId);
        setX(x);
        setY(y);
        setAngle(angle);
        setVehicleType(vehicleType);
        setSpeed(speed);
        setPos(pos);
        setLane(lane);
        setSlope(slope);
        setSimtime(simtime);
        setInjected(injected);
        resetChangedOnNotNull();
    }
}
