/*
 * This file is generated by jOOQ.
 */
package uk.ncl.giacomobergami.utils.database.jooq.tables.records;


import org.jooq.impl.TableRecordImpl;

import uk.ncl.giacomobergami.utils.database.jooq.tables.BandwidthshareinfoImport;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class BandwidthshareinfoImportRecord extends TableRecordImpl<BandwidthshareinfoImportRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.bandwidthshareinfo_import.bandwidthshare</code>.
     */
    public void setBandwidthshare(Double value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.bandwidthshareinfo_import.bandwidthshare</code>.
     */
    public Double getBandwidthshare() {
        return (Double) get(0);
    }

    /**
     * Setter for <code>public.bandwidthshareinfo_import.channelid</code>.
     */
    public void setChannelid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.bandwidthshareinfo_import.channelid</code>.
     */
    public String getChannelid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.bandwidthshareinfo_import.edgename</code>.
     */
    public void setEdgename(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.bandwidthshareinfo_import.edgename</code>.
     */
    public String getEdgename() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.bandwidthshareinfo_import.melname</code>.
     */
    public void setMelname(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.bandwidthshareinfo_import.melname</code>.
     */
    public String getMelname() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.bandwidthshareinfo_import.timestamp</code>.
     */
    public void setTimestamp(Double value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.bandwidthshareinfo_import.timestamp</code>.
     */
    public Double getTimestamp() {
        return (Double) get(4);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BandwidthshareinfoImportRecord
     */
    public BandwidthshareinfoImportRecord() {
        super(BandwidthshareinfoImport.BANDWIDTHSHAREINFO_IMPORT);
    }

    /**
     * Create a detached, initialised BandwidthshareinfoImportRecord
     */
    public BandwidthshareinfoImportRecord(Double bandwidthshare, String channelid, String edgename, String melname, Double timestamp) {
        super(BandwidthshareinfoImport.BANDWIDTHSHAREINFO_IMPORT);

        setBandwidthshare(bandwidthshare);
        setChannelid(channelid);
        setEdgename(edgename);
        setMelname(melname);
        setTimestamp(timestamp);
        resetChangedOnNotNull();
    }
}
