/*
 * This file is generated by jOOQ.
 */
package uk.ncl.giacomobergami.utils.database.jooq.tables.records;


import org.jooq.impl.TableRecordImpl;

import uk.ncl.giacomobergami.utils.database.jooq.tables.ConnectionpersimtimeImport;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ConnectionpersimtimeImportRecord extends TableRecordImpl<ConnectionpersimtimeImportRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.connectionpersimtime_import.iotdevices</code>.
     */
    public void setIotdevices(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.connectionpersimtime_import.iotdevices</code>.
     */
    public Integer getIotdevices() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.connectionpersimtime_import.edgehost</code>.
     */
    public void setEdgehost(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.connectionpersimtime_import.edgehost</code>.
     */
    public String getEdgehost() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.connectionpersimtime_import.cps_time</code>.
     */
    public void setCpsTime(Double value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.connectionpersimtime_import.cps_time</code>.
     */
    public Double getCpsTime() {
        return (Double) get(2);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ConnectionpersimtimeImportRecord
     */
    public ConnectionpersimtimeImportRecord() {
        super(ConnectionpersimtimeImport.CONNECTIONPERSIMTIME_IMPORT);
    }

    /**
     * Create a detached, initialised ConnectionpersimtimeImportRecord
     */
    public ConnectionpersimtimeImportRecord(Integer iotdevices, String edgehost, Double cpsTime) {
        super(ConnectionpersimtimeImport.CONNECTIONPERSIMTIME_IMPORT);

        setIotdevices(iotdevices);
        setEdgehost(edgehost);
        setCpsTime(cpsTime);
        resetChangedOnNotNull();
    }
}
