/*
 * This file is generated by jOOQ.
 */
package uk.ncl.giacomobergami.utils.database.jooq.tables.records;


import org.jooq.impl.TableRecordImpl;

import uk.ncl.giacomobergami.utils.database.jooq.tables.DatacenterenergyconsumptionImport;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DatacenterenergyconsumptionImportRecord extends TableRecordImpl<DatacenterenergyconsumptionImportRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for
     * <code>public.datacenterenergyconsumption_import.hostenergyconsumed</code>.
     */
    public void setHostenergyconsumed(Double value) {
        set(0, value);
    }

    /**
     * Getter for
     * <code>public.datacenterenergyconsumption_import.hostenergyconsumed</code>.
     */
    public Double getHostenergyconsumed() {
        return (Double) get(0);
    }

    /**
     * Setter for
     * <code>public.datacenterenergyconsumption_import.switchenergyconsumed</code>.
     */
    public void setSwitchenergyconsumed(Double value) {
        set(1, value);
    }

    /**
     * Getter for
     * <code>public.datacenterenergyconsumption_import.switchenergyconsumed</code>.
     */
    public Double getSwitchenergyconsumed() {
        return (Double) get(1);
    }

    /**
     * Setter for
     * <code>public.datacenterenergyconsumption_import.totalenergyconsumed</code>.
     */
    public void setTotalenergyconsumed(Double value) {
        set(2, value);
    }

    /**
     * Getter for
     * <code>public.datacenterenergyconsumption_import.totalenergyconsumed</code>.
     */
    public Double getTotalenergyconsumed() {
        return (Double) get(2);
    }

    /**
     * Setter for <code>public.datacenterenergyconsumption_import.dcname</code>.
     */
    public void setDcname(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.datacenterenergyconsumption_import.dcname</code>.
     */
    public String getDcname() {
        return (String) get(3);
    }

    /**
     * Setter for
     * <code>public.datacenterenergyconsumption_import.finishtime</code>.
     */
    public void setFinishtime(Double value) {
        set(4, value);
    }

    /**
     * Getter for
     * <code>public.datacenterenergyconsumption_import.finishtime</code>.
     */
    public Double getFinishtime() {
        return (Double) get(4);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DatacenterenergyconsumptionImportRecord
     */
    public DatacenterenergyconsumptionImportRecord() {
        super(DatacenterenergyconsumptionImport.DATACENTERENERGYCONSUMPTION_IMPORT);
    }

    /**
     * Create a detached, initialised DatacenterenergyconsumptionImportRecord
     */
    public DatacenterenergyconsumptionImportRecord(Double hostenergyconsumed, Double switchenergyconsumed, Double totalenergyconsumed, String dcname, Double finishtime) {
        super(DatacenterenergyconsumptionImport.DATACENTERENERGYCONSUMPTION_IMPORT);

        setHostenergyconsumed(hostenergyconsumed);
        setSwitchenergyconsumed(switchenergyconsumed);
        setTotalenergyconsumed(totalenergyconsumed);
        setDcname(dcname);
        setFinishtime(finishtime);
        resetChangedOnNotNull();
    }
}
