/*
 * This file is generated by jOOQ.
 */
package uk.ncl.giacomobergami.utils.database.jooq.tables.records;


import org.jooq.impl.TableRecordImpl;

import uk.ncl.giacomobergami.utils.database.jooq.tables.HistoryentryImport;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class HistoryentryImportRecord extends TableRecordImpl<HistoryentryImportRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.historyentry_import.numactiveports</code>.
     */
    public void setNumactiveports(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.historyentry_import.numactiveports</code>.
     */
    public Integer getNumactiveports() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.historyentry_import.starttime</code>.
     */
    public void setStarttime(Double value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.historyentry_import.starttime</code>.
     */
    public Double getStarttime() {
        return (Double) get(1);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached HistoryentryImportRecord
     */
    public HistoryentryImportRecord() {
        super(HistoryentryImport.HISTORYENTRY_IMPORT);
    }

    /**
     * Create a detached, initialised HistoryentryImportRecord
     */
    public HistoryentryImportRecord(Integer numactiveports, Double starttime) {
        super(HistoryentryImport.HISTORYENTRY_IMPORT);

        setNumactiveports(numactiveports);
        setStarttime(starttime);
        resetChangedOnNotNull();
    }
}
