/*
 * This file is generated by jOOQ.
 */
package uk.ncl.giacomobergami.utils.database.jooq.tables.records;


import org.jooq.impl.TableRecordImpl;

import uk.ncl.giacomobergami.utils.database.jooq.tables.HostpowerconsumptionImport;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class HostpowerconsumptionImportRecord extends TableRecordImpl<HostpowerconsumptionImportRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.hostpowerconsumption_import.dcname</code>.
     */
    public void setDcname(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.hostpowerconsumption_import.dcname</code>.
     */
    public String getDcname() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.hostpowerconsumption_import.energy</code>.
     */
    public void setEnergy(Double value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.hostpowerconsumption_import.energy</code>.
     */
    public Double getEnergy() {
        return (Double) get(1);
    }

    /**
     * Setter for <code>public.hostpowerconsumption_import.hpc_name</code>.
     */
    public void setHpcName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.hostpowerconsumption_import.hpc_name</code>.
     */
    public String getHpcName() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached HostpowerconsumptionImportRecord
     */
    public HostpowerconsumptionImportRecord() {
        super(HostpowerconsumptionImport.HOSTPOWERCONSUMPTION_IMPORT);
    }

    /**
     * Create a detached, initialised HostpowerconsumptionImportRecord
     */
    public HostpowerconsumptionImportRecord(String dcname, Double energy, String hpcName) {
        super(HostpowerconsumptionImport.HOSTPOWERCONSUMPTION_IMPORT);

        setDcname(dcname);
        setEnergy(energy);
        setHpcName(hpcName);
        resetChangedOnNotNull();
    }
}
