/*
 * This file is generated by jOOQ.
 */
package uk.ncl.giacomobergami.utils.database.jooq.tables.records;


import org.jooq.impl.TableRecordImpl;

import uk.ncl.giacomobergami.utils.database.jooq.tables.OverallappresultsImport;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class OverallappresultsImportRecord extends TableRecordImpl<OverallappresultsImportRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.overallappresults_import.appname</code>.
     */
    public void setAppname(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.overallappresults_import.appname</code>.
     */
    public String getAppname() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.overallappresults_import.endtime</code>.
     */
    public void setEndtime(Double value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.overallappresults_import.endtime</code>.
     */
    public Double getEndtime() {
        return (Double) get(1);
    }

    /**
     * Setter for
     * <code>public.overallappresults_import.iotdevicebatteryconsumption</code>.
     */
    public void setIotdevicebatteryconsumption(Double value) {
        set(2, value);
    }

    /**
     * Getter for
     * <code>public.overallappresults_import.iotdevicebatteryconsumption</code>.
     */
    public Double getIotdevicebatteryconsumption() {
        return (Double) get(2);
    }

    /**
     * Setter for <code>public.overallappresults_import.iotdevicedrained</code>.
     */
    public void setIotdevicedrained(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.overallappresults_import.iotdevicedrained</code>.
     */
    public String getIotdevicedrained() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.overallappresults_import.simulationtime</code>.
     */
    public void setSimulationtime(Double value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.overallappresults_import.simulationtime</code>.
     */
    public Double getSimulationtime() {
        return (Double) get(4);
    }

    /**
     * Setter for <code>public.overallappresults_import.starttime</code>.
     */
    public void setStarttime(Double value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.overallappresults_import.starttime</code>.
     */
    public Double getStarttime() {
        return (Double) get(5);
    }

    /**
     * Setter for
     * <code>public.overallappresults_import.totalcloudletsizes</code>.
     */
    public void setTotalcloudletsizes(Integer value) {
        set(6, value);
    }

    /**
     * Getter for
     * <code>public.overallappresults_import.totalcloudletsizes</code>.
     */
    public Integer getTotalcloudletsizes() {
        return (Integer) get(6);
    }

    /**
     * Setter for
     * <code>public.overallappresults_import.totaledgeletsizes</code>.
     */
    public void setTotaledgeletsizes(Integer value) {
        set(7, value);
    }

    /**
     * Getter for
     * <code>public.overallappresults_import.totaledgeletsizes</code>.
     */
    public Integer getTotaledgeletsizes() {
        return (Integer) get(7);
    }

    /**
     * Setter for
     * <code>public.overallappresults_import.totaliotgenerateddata</code>.
     */
    public void setTotaliotgenerateddata(Integer value) {
        set(8, value);
    }

    /**
     * Getter for
     * <code>public.overallappresults_import.totaliotgenerateddata</code>.
     */
    public Integer getTotaliotgenerateddata() {
        return (Integer) get(8);
    }

    /**
     * Setter for
     * <code>public.overallappresults_import.totalmelgenerateddata</code>.
     */
    public void setTotalmelgenerateddata(Integer value) {
        set(9, value);
    }

    /**
     * Getter for
     * <code>public.overallappresults_import.totalmelgenerateddata</code>.
     */
    public Integer getTotalmelgenerateddata() {
        return (Integer) get(9);
    }

    /**
     * Setter for
     * <code>public.overallappresults_import.apptotalrunningtime</code>.
     */
    public void setApptotalrunningtime(Double value) {
        set(10, value);
    }

    /**
     * Getter for
     * <code>public.overallappresults_import.apptotalrunningtime</code>.
     */
    public Double getApptotalrunningtime() {
        return (Double) get(10);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OverallappresultsImportRecord
     */
    public OverallappresultsImportRecord() {
        super(OverallappresultsImport.OVERALLAPPRESULTS_IMPORT);
    }

    /**
     * Create a detached, initialised OverallappresultsImportRecord
     */
    public OverallappresultsImportRecord(String appname, Double endtime, Double iotdevicebatteryconsumption, String iotdevicedrained, Double simulationtime, Double starttime, Integer totalcloudletsizes, Integer totaledgeletsizes, Integer totaliotgenerateddata, Integer totalmelgenerateddata, Double apptotalrunningtime) {
        super(OverallappresultsImport.OVERALLAPPRESULTS_IMPORT);

        setAppname(appname);
        setEndtime(endtime);
        setIotdevicebatteryconsumption(iotdevicebatteryconsumption);
        setIotdevicedrained(iotdevicedrained);
        setSimulationtime(simulationtime);
        setStarttime(starttime);
        setTotalcloudletsizes(totalcloudletsizes);
        setTotaledgeletsizes(totaledgeletsizes);
        setTotaliotgenerateddata(totaliotgenerateddata);
        setTotalmelgenerateddata(totalmelgenerateddata);
        setApptotalrunningtime(apptotalrunningtime);
        resetChangedOnNotNull();
    }
}
