/*
 * This file is generated by jOOQ.
 */
package uk.ncl.giacomobergami.utils.database.jooq.tables.records;


import org.jooq.impl.TableRecordImpl;

import uk.ncl.giacomobergami.utils.database.jooq.tables.PowerutilisationhistoryImport;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PowerutilisationhistoryImportRecord extends TableRecordImpl<PowerutilisationhistoryImportRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.powerutilisationhistory_import.dcname</code>.
     */
    public void setDcname(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.powerutilisationhistory_import.dcname</code>.
     */
    public String getDcname() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.powerutilisationhistory_import.puh_name</code>.
     */
    public void setPuhName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.powerutilisationhistory_import.puh_name</code>.
     */
    public String getPuhName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.powerutilisationhistory_import.starttime</code>.
     */
    public void setStarttime(Double value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.powerutilisationhistory_import.starttime</code>.
     */
    public Double getStarttime() {
        return (Double) get(2);
    }

    /**
     * Setter for <code>public.powerutilisationhistory_import.usedmips</code>.
     */
    public void setUsedmips(Double value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.powerutilisationhistory_import.usedmips</code>.
     */
    public Double getUsedmips() {
        return (Double) get(3);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PowerutilisationhistoryImportRecord
     */
    public PowerutilisationhistoryImportRecord() {
        super(PowerutilisationhistoryImport.POWERUTILISATIONHISTORY_IMPORT);
    }

    /**
     * Create a detached, initialised PowerutilisationhistoryImportRecord
     */
    public PowerutilisationhistoryImportRecord(String dcname, String puhName, Double starttime, Double usedmips) {
        super(PowerutilisationhistoryImport.POWERUTILISATIONHISTORY_IMPORT);

        setDcname(dcname);
        setPuhName(puhName);
        setStarttime(starttime);
        setUsedmips(usedmips);
        resetChangedOnNotNull();
    }
}
