/*
 * This file is generated by jOOQ.
 */
package uk.ncl.giacomobergami.utils.database.jooq.tables.records;


import org.jooq.impl.TableRecordImpl;

import uk.ncl.giacomobergami.utils.database.jooq.tables.RsuinformationImport;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RsuinformationImportRecord extends TableRecordImpl<RsuinformationImportRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.rsuinformation_import.x</code>.
     */
    public void setX(Double value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.rsuinformation_import.x</code>.
     */
    public Double getX() {
        return (Double) get(0);
    }

    /**
     * Setter for <code>public.rsuinformation_import.y</code>.
     */
    public void setY(Double value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.rsuinformation_import.y</code>.
     */
    public Double getY() {
        return (Double) get(1);
    }

    /**
     * Setter for <code>public.rsuinformation_import.simtime</code>.
     */
    public void setSimtime(Double value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.rsuinformation_import.simtime</code>.
     */
    public Double getSimtime() {
        return (Double) get(2);
    }

    /**
     * Setter for
     * <code>public.rsuinformation_import.communication_radius</code>.
     */
    public void setCommunicationRadius(Double value) {
        set(3, value);
    }

    /**
     * Getter for
     * <code>public.rsuinformation_import.communication_radius</code>.
     */
    public Double getCommunicationRadius() {
        return (Double) get(3);
    }

    /**
     * Setter for
     * <code>public.rsuinformation_import.max_vehicle_communication</code>.
     */
    public void setMaxVehicleCommunication(Double value) {
        set(4, value);
    }

    /**
     * Getter for
     * <code>public.rsuinformation_import.max_vehicle_communication</code>.
     */
    public Double getMaxVehicleCommunication() {
        return (Double) get(4);
    }

    /**
     * Setter for <code>public.rsuinformation_import.rsu_id</code>.
     */
    public void setRsuId(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.rsuinformation_import.rsu_id</code>.
     */
    public String getRsuId() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RsuinformationImportRecord
     */
    public RsuinformationImportRecord() {
        super(RsuinformationImport.RSUINFORMATION_IMPORT);
    }

    /**
     * Create a detached, initialised RsuinformationImportRecord
     */
    public RsuinformationImportRecord(Double x, Double y, Double simtime, Double communicationRadius, Double maxVehicleCommunication, String rsuId) {
        super(RsuinformationImport.RSUINFORMATION_IMPORT);

        setX(x);
        setY(y);
        setSimtime(simtime);
        setCommunicationRadius(communicationRadius);
        setMaxVehicleCommunication(maxVehicleCommunication);
        setRsuId(rsuId);
        resetChangedOnNotNull();
    }
}
