/*
 * This file is generated by jOOQ.
 */
package uk.ncl.giacomobergami.utils.database.jooq.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import uk.ncl.giacomobergami.utils.database.jooq.tables.Sourcetodestlinks;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SourcetodestlinksRecord extends UpdatableRecordImpl<SourcetodestlinksRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.sourcetodestlinks.unique_entry_id</code>.
     */
    public void setUniqueEntryId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.sourcetodestlinks.unique_entry_id</code>.
     */
    public Integer getUniqueEntryId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.sourcetodestlinks.topology_id</code>.
     */
    public void setTopologyId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.sourcetodestlinks.topology_id</code>.
     */
    public Integer getTopologyId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.sourcetodestlinks.link_id</code>.
     */
    public void setLinkId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.sourcetodestlinks.link_id</code>.
     */
    public Integer getLinkId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.sourcetodestlinks.from_id</code>.
     */
    public void setFromId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.sourcetodestlinks.from_id</code>.
     */
    public Integer getFromId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.sourcetodestlinks.to_id</code>.
     */
    public void setToId(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.sourcetodestlinks.to_id</code>.
     */
    public Integer getToId() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.sourcetodestlinks.bw</code>.
     */
    public void setBw(Double value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.sourcetodestlinks.bw</code>.
     */
    public Double getBw() {
        return (Double) get(5);
    }

    /**
     * Setter for <code>public.sourcetodestlinks.nochannels</code>.
     */
    public void setNochannels(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.sourcetodestlinks.nochannels</code>.
     */
    public Integer getNochannels() {
        return (Integer) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SourcetodestlinksRecord
     */
    public SourcetodestlinksRecord() {
        super(Sourcetodestlinks.SOURCETODESTLINKS);
    }

    /**
     * Create a detached, initialised SourcetodestlinksRecord
     */
    public SourcetodestlinksRecord(Integer uniqueEntryId, Integer topologyId, Integer linkId, Integer fromId, Integer toId, Double bw, Integer nochannels) {
        super(Sourcetodestlinks.SOURCETODESTLINKS);

        setUniqueEntryId(uniqueEntryId);
        setTopologyId(topologyId);
        setLinkId(linkId);
        setFromId(fromId);
        setToId(toId);
        setBw(bw);
        setNochannels(nochannels);
        resetChangedOnNotNull();
    }
}
