/*
 * This file is generated by jOOQ.
 */
package uk.ncl.giacomobergami.utils.database.jooq.tables.records;


import org.jooq.impl.TableRecordImpl;

import uk.ncl.giacomobergami.utils.database.jooq.tables.SwitchpowerconsumptionImport;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SwitchpowerconsumptionImportRecord extends TableRecordImpl<SwitchpowerconsumptionImportRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.switchpowerconsumption_import.dcname</code>.
     */
    public void setDcname(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.switchpowerconsumption_import.dcname</code>.
     */
    public String getDcname() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.switchpowerconsumption_import.energy</code>.
     */
    public void setEnergy(Double value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.switchpowerconsumption_import.energy</code>.
     */
    public Double getEnergy() {
        return (Double) get(1);
    }

    /**
     * Setter for <code>public.switchpowerconsumption_import.spc_name</code>.
     */
    public void setSpcName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.switchpowerconsumption_import.spc_name</code>.
     */
    public String getSpcName() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SwitchpowerconsumptionImportRecord
     */
    public SwitchpowerconsumptionImportRecord() {
        super(SwitchpowerconsumptionImport.SWITCHPOWERCONSUMPTION_IMPORT);
    }

    /**
     * Create a detached, initialised SwitchpowerconsumptionImportRecord
     */
    public SwitchpowerconsumptionImportRecord(String dcname, Double energy, String spcName) {
        super(SwitchpowerconsumptionImport.SWITCHPOWERCONSUMPTION_IMPORT);

        setDcname(dcname);
        setEnergy(energy);
        setSpcName(spcName);
        resetChangedOnNotNull();
    }
}
