walking: "https://archive.newcastle.urbanobservatory.ac.uk/file/month_file/2025-2-Walking.csv.zip"
vehicles: "https://archive.newcastle.urbanobservatory.ac.uk/file/month_file/2025-2-Plates%20Matching.csv.zip"
netconvert_binary: "/usr/bin/netconvert"
place_name: "Newcastle Upon Tyne"
aggregate_edges_to_nodes: yes
velocity_unit: "mph"
sumo:
  ignore_links:
    - 'highway.bridleway'
    - 'highway.cycleway'
    - 'highway.footway'
    - 'highway.pedestrian'
    - 'highway.service'
    - 'highway.path'
  allowed:
    - 'evehicle'
pedestrian_fields:
  sensor_id: "Raw ID"
  sensor_name: "Sensor Name"
  lon: "Sensor Centroid Longitude"
  lat: "Sensor Centroid Latitude"
  time: "Timestamp"
  count: "Value"
vehicular_fields:
  sensor_id: "Raw ID"
  sensor_name: "Sensor Name"
  lon: "Sensor Centroid Longitude"
  lat: "Sensor Centroid Latitude"
  time: "Timestamp"
  count: "Value"
#chargers:
#  maxresults: 1000000
#  countrycode: "GB"
#  latitude: 54.966667
#  longitude: -1.6
#  distance: 100
#  distanceunit: "km"
#  verbose: yes
#  key: "4da63093-c085-4b7f-9b65-ce6f2229918b"