/*
 * This file is generated by jOOQ.
 */
package uk.ncl.giacomobergami.utils.database.jooq;


import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import uk.ncl.giacomobergami.utils.database.jooq.tables.Accuratebatteryinfo;
import uk.ncl.giacomobergami.utils.database.jooq.tables.AccuratebatteryinfoImport;
import uk.ncl.giacomobergami.utils.database.jooq.tables.Ambulanceinformation;
import uk.ncl.giacomobergami.utils.database.jooq.tables.AmbulanceinformationImport;
import uk.ncl.giacomobergami.utils.database.jooq.tables.Applist;
import uk.ncl.giacomobergami.utils.database.jooq.tables.ApplistImport;
import uk.ncl.giacomobergami.utils.database.jooq.tables.Bandwidthshareinfo;
import uk.ncl.giacomobergami.utils.database.jooq.tables.BandwidthshareinfoImport;
import uk.ncl.giacomobergami.utils.database.jooq.tables.Connectionpersimtime;
import uk.ncl.giacomobergami.utils.database.jooq.tables.ConnectionpersimtimeImport;
import uk.ncl.giacomobergami.utils.database.jooq.tables.Datacenterenergyconsumption;
import uk.ncl.giacomobergami.utils.database.jooq.tables.DatacenterenergyconsumptionImport;
import uk.ncl.giacomobergami.utils.database.jooq.tables.Historyentry;
import uk.ncl.giacomobergami.utils.database.jooq.tables.HistoryentryImport;
import uk.ncl.giacomobergami.utils.database.jooq.tables.Hostpowerconsumption;
import uk.ncl.giacomobergami.utils.database.jooq.tables.HostpowerconsumptionImport;
import uk.ncl.giacomobergami.utils.database.jooq.tables.Neighbourschange;
import uk.ncl.giacomobergami.utils.database.jooq.tables.Osmoticappsstats;
import uk.ncl.giacomobergami.utils.database.jooq.tables.OsmoticappsstatsImport;
import uk.ncl.giacomobergami.utils.database.jooq.tables.Overallappresults;
import uk.ncl.giacomobergami.utils.database.jooq.tables.OverallappresultsImport;
import uk.ncl.giacomobergami.utils.database.jooq.tables.Powerutilisationhistory;
import uk.ncl.giacomobergami.utils.database.jooq.tables.PowerutilisationhistoryImport;
import uk.ncl.giacomobergami.utils.database.jooq.tables.Rsuinformation;
import uk.ncl.giacomobergami.utils.database.jooq.tables.RsuinformationImport;
import uk.ncl.giacomobergami.utils.database.jooq.tables.Sourcetodestlinks;
import uk.ncl.giacomobergami.utils.database.jooq.tables.Switchpowerconsumption;
import uk.ncl.giacomobergami.utils.database.jooq.tables.SwitchpowerconsumptionImport;
import uk.ncl.giacomobergami.utils.database.jooq.tables.TimedScc;
import uk.ncl.giacomobergami.utils.database.jooq.tables.Vehinformation;
import uk.ncl.giacomobergami.utils.database.jooq.tables.VehinformationImport;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.accuratebatteryinfo</code>.
     */
    public final Accuratebatteryinfo ACCURATEBATTERYINFO = Accuratebatteryinfo.ACCURATEBATTERYINFO;

    /**
     * The table <code>public.accuratebatteryinfo_import</code>.
     */
    public final AccuratebatteryinfoImport ACCURATEBATTERYINFO_IMPORT = AccuratebatteryinfoImport.ACCURATEBATTERYINFO_IMPORT;

    /**
     * The table <code>public.ambulanceinformation</code>.
     */
    public final Ambulanceinformation AMBULANCEINFORMATION = Ambulanceinformation.AMBULANCEINFORMATION;

    /**
     * The table <code>public.ambulanceinformation_import</code>.
     */
    public final AmbulanceinformationImport AMBULANCEINFORMATION_IMPORT = AmbulanceinformationImport.AMBULANCEINFORMATION_IMPORT;

    /**
     * The table <code>public.applist</code>.
     */
    public final Applist APPLIST = Applist.APPLIST;

    /**
     * The table <code>public.applist_import</code>.
     */
    public final ApplistImport APPLIST_IMPORT = ApplistImport.APPLIST_IMPORT;

    /**
     * The table <code>public.bandwidthshareinfo</code>.
     */
    public final Bandwidthshareinfo BANDWIDTHSHAREINFO = Bandwidthshareinfo.BANDWIDTHSHAREINFO;

    /**
     * The table <code>public.bandwidthshareinfo_import</code>.
     */
    public final BandwidthshareinfoImport BANDWIDTHSHAREINFO_IMPORT = BandwidthshareinfoImport.BANDWIDTHSHAREINFO_IMPORT;

    /**
     * The table <code>public.connectionpersimtime</code>.
     */
    public final Connectionpersimtime CONNECTIONPERSIMTIME = Connectionpersimtime.CONNECTIONPERSIMTIME;

    /**
     * The table <code>public.connectionpersimtime_import</code>.
     */
    public final ConnectionpersimtimeImport CONNECTIONPERSIMTIME_IMPORT = ConnectionpersimtimeImport.CONNECTIONPERSIMTIME_IMPORT;

    /**
     * The table <code>public.datacenterenergyconsumption</code>.
     */
    public final Datacenterenergyconsumption DATACENTERENERGYCONSUMPTION = Datacenterenergyconsumption.DATACENTERENERGYCONSUMPTION;

    /**
     * The table <code>public.datacenterenergyconsumption_import</code>.
     */
    public final DatacenterenergyconsumptionImport DATACENTERENERGYCONSUMPTION_IMPORT = DatacenterenergyconsumptionImport.DATACENTERENERGYCONSUMPTION_IMPORT;

    /**
     * The table <code>public.historyentry</code>.
     */
    public final Historyentry HISTORYENTRY = Historyentry.HISTORYENTRY;

    /**
     * The table <code>public.historyentry_import</code>.
     */
    public final HistoryentryImport HISTORYENTRY_IMPORT = HistoryentryImport.HISTORYENTRY_IMPORT;

    /**
     * The table <code>public.hostpowerconsumption</code>.
     */
    public final Hostpowerconsumption HOSTPOWERCONSUMPTION = Hostpowerconsumption.HOSTPOWERCONSUMPTION;

    /**
     * The table <code>public.hostpowerconsumption_import</code>.
     */
    public final HostpowerconsumptionImport HOSTPOWERCONSUMPTION_IMPORT = HostpowerconsumptionImport.HOSTPOWERCONSUMPTION_IMPORT;

    /**
     * The table <code>public.neighbourschange</code>.
     */
    public final Neighbourschange NEIGHBOURSCHANGE = Neighbourschange.NEIGHBOURSCHANGE;

    /**
     * The table <code>public.osmoticappsstats</code>.
     */
    public final Osmoticappsstats OSMOTICAPPSSTATS = Osmoticappsstats.OSMOTICAPPSSTATS;

    /**
     * The table <code>public.osmoticappsstats_import</code>.
     */
    public final OsmoticappsstatsImport OSMOTICAPPSSTATS_IMPORT = OsmoticappsstatsImport.OSMOTICAPPSSTATS_IMPORT;

    /**
     * The table <code>public.overallappresults</code>.
     */
    public final Overallappresults OVERALLAPPRESULTS = Overallappresults.OVERALLAPPRESULTS;

    /**
     * The table <code>public.overallappresults_import</code>.
     */
    public final OverallappresultsImport OVERALLAPPRESULTS_IMPORT = OverallappresultsImport.OVERALLAPPRESULTS_IMPORT;

    /**
     * The table <code>public.powerutilisationhistory</code>.
     */
    public final Powerutilisationhistory POWERUTILISATIONHISTORY = Powerutilisationhistory.POWERUTILISATIONHISTORY;

    /**
     * The table <code>public.powerutilisationhistory_import</code>.
     */
    public final PowerutilisationhistoryImport POWERUTILISATIONHISTORY_IMPORT = PowerutilisationhistoryImport.POWERUTILISATIONHISTORY_IMPORT;

    /**
     * The table <code>public.rsuinformation</code>.
     */
    public final Rsuinformation RSUINFORMATION = Rsuinformation.RSUINFORMATION;

    /**
     * The table <code>public.rsuinformation_import</code>.
     */
    public final RsuinformationImport RSUINFORMATION_IMPORT = RsuinformationImport.RSUINFORMATION_IMPORT;

    /**
     * The table <code>public.sourcetodestlinks</code>.
     */
    public final Sourcetodestlinks SOURCETODESTLINKS = Sourcetodestlinks.SOURCETODESTLINKS;

    /**
     * The table <code>public.switchpowerconsumption</code>.
     */
    public final Switchpowerconsumption SWITCHPOWERCONSUMPTION = Switchpowerconsumption.SWITCHPOWERCONSUMPTION;

    /**
     * The table <code>public.switchpowerconsumption_import</code>.
     */
    public final SwitchpowerconsumptionImport SWITCHPOWERCONSUMPTION_IMPORT = SwitchpowerconsumptionImport.SWITCHPOWERCONSUMPTION_IMPORT;

    /**
     * The table <code>public.timed_scc</code>.
     */
    public final TimedScc TIMED_SCC = TimedScc.TIMED_SCC;

    /**
     * The table <code>public.vehinformation</code>.
     */
    public final Vehinformation VEHINFORMATION = Vehinformation.VEHINFORMATION;

    /**
     * The table <code>public.vehinformation_import</code>.
     */
    public final VehinformationImport VEHINFORMATION_IMPORT = VehinformationImport.VEHINFORMATION_IMPORT;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Accuratebatteryinfo.ACCURATEBATTERYINFO,
            AccuratebatteryinfoImport.ACCURATEBATTERYINFO_IMPORT,
            Ambulanceinformation.AMBULANCEINFORMATION,
            AmbulanceinformationImport.AMBULANCEINFORMATION_IMPORT,
            Applist.APPLIST,
            ApplistImport.APPLIST_IMPORT,
            Bandwidthshareinfo.BANDWIDTHSHAREINFO,
            BandwidthshareinfoImport.BANDWIDTHSHAREINFO_IMPORT,
            Connectionpersimtime.CONNECTIONPERSIMTIME,
            ConnectionpersimtimeImport.CONNECTIONPERSIMTIME_IMPORT,
            Datacenterenergyconsumption.DATACENTERENERGYCONSUMPTION,
            DatacenterenergyconsumptionImport.DATACENTERENERGYCONSUMPTION_IMPORT,
            Historyentry.HISTORYENTRY,
            HistoryentryImport.HISTORYENTRY_IMPORT,
            Hostpowerconsumption.HOSTPOWERCONSUMPTION,
            HostpowerconsumptionImport.HOSTPOWERCONSUMPTION_IMPORT,
            Neighbourschange.NEIGHBOURSCHANGE,
            Osmoticappsstats.OSMOTICAPPSSTATS,
            OsmoticappsstatsImport.OSMOTICAPPSSTATS_IMPORT,
            Overallappresults.OVERALLAPPRESULTS,
            OverallappresultsImport.OVERALLAPPRESULTS_IMPORT,
            Powerutilisationhistory.POWERUTILISATIONHISTORY,
            PowerutilisationhistoryImport.POWERUTILISATIONHISTORY_IMPORT,
            Rsuinformation.RSUINFORMATION,
            RsuinformationImport.RSUINFORMATION_IMPORT,
            Sourcetodestlinks.SOURCETODESTLINKS,
            Switchpowerconsumption.SWITCHPOWERCONSUMPTION,
            SwitchpowerconsumptionImport.SWITCHPOWERCONSUMPTION_IMPORT,
            TimedScc.TIMED_SCC,
            Vehinformation.VEHINFORMATION,
            VehinformationImport.VEHINFORMATION_IMPORT
        );
    }
}
