/*
 * This file is generated by jOOQ.
 */
package uk.ncl.giacomobergami.utils.database.jooq;


import uk.ncl.giacomobergami.utils.database.jooq.tables.Accuratebatteryinfo;
import uk.ncl.giacomobergami.utils.database.jooq.tables.AccuratebatteryinfoImport;
import uk.ncl.giacomobergami.utils.database.jooq.tables.Ambulanceinformation;
import uk.ncl.giacomobergami.utils.database.jooq.tables.AmbulanceinformationImport;
import uk.ncl.giacomobergami.utils.database.jooq.tables.Applist;
import uk.ncl.giacomobergami.utils.database.jooq.tables.ApplistImport;
import uk.ncl.giacomobergami.utils.database.jooq.tables.Bandwidthshareinfo;
import uk.ncl.giacomobergami.utils.database.jooq.tables.BandwidthshareinfoImport;
import uk.ncl.giacomobergami.utils.database.jooq.tables.Connectionpersimtime;
import uk.ncl.giacomobergami.utils.database.jooq.tables.ConnectionpersimtimeImport;
import uk.ncl.giacomobergami.utils.database.jooq.tables.Datacenterenergyconsumption;
import uk.ncl.giacomobergami.utils.database.jooq.tables.DatacenterenergyconsumptionImport;
import uk.ncl.giacomobergami.utils.database.jooq.tables.Historyentry;
import uk.ncl.giacomobergami.utils.database.jooq.tables.HistoryentryImport;
import uk.ncl.giacomobergami.utils.database.jooq.tables.Hostpowerconsumption;
import uk.ncl.giacomobergami.utils.database.jooq.tables.HostpowerconsumptionImport;
import uk.ncl.giacomobergami.utils.database.jooq.tables.Neighbourschange;
import uk.ncl.giacomobergami.utils.database.jooq.tables.Osmoticappsstats;
import uk.ncl.giacomobergami.utils.database.jooq.tables.OsmoticappsstatsImport;
import uk.ncl.giacomobergami.utils.database.jooq.tables.Overallappresults;
import uk.ncl.giacomobergami.utils.database.jooq.tables.OverallappresultsImport;
import uk.ncl.giacomobergami.utils.database.jooq.tables.Powerutilisationhistory;
import uk.ncl.giacomobergami.utils.database.jooq.tables.PowerutilisationhistoryImport;
import uk.ncl.giacomobergami.utils.database.jooq.tables.Rsuinformation;
import uk.ncl.giacomobergami.utils.database.jooq.tables.RsuinformationImport;
import uk.ncl.giacomobergami.utils.database.jooq.tables.Sourcetodestlinks;
import uk.ncl.giacomobergami.utils.database.jooq.tables.Switchpowerconsumption;
import uk.ncl.giacomobergami.utils.database.jooq.tables.SwitchpowerconsumptionImport;
import uk.ncl.giacomobergami.utils.database.jooq.tables.TimedScc;
import uk.ncl.giacomobergami.utils.database.jooq.tables.Vehinformation;
import uk.ncl.giacomobergami.utils.database.jooq.tables.VehinformationImport;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.accuratebatteryinfo</code>.
     */
    public static final Accuratebatteryinfo ACCURATEBATTERYINFO = Accuratebatteryinfo.ACCURATEBATTERYINFO;

    /**
     * The table <code>public.accuratebatteryinfo_import</code>.
     */
    public static final AccuratebatteryinfoImport ACCURATEBATTERYINFO_IMPORT = AccuratebatteryinfoImport.ACCURATEBATTERYINFO_IMPORT;

    /**
     * The table <code>public.ambulanceinformation</code>.
     */
    public static final Ambulanceinformation AMBULANCEINFORMATION = Ambulanceinformation.AMBULANCEINFORMATION;

    /**
     * The table <code>public.ambulanceinformation_import</code>.
     */
    public static final AmbulanceinformationImport AMBULANCEINFORMATION_IMPORT = AmbulanceinformationImport.AMBULANCEINFORMATION_IMPORT;

    /**
     * The table <code>public.applist</code>.
     */
    public static final Applist APPLIST = Applist.APPLIST;

    /**
     * The table <code>public.applist_import</code>.
     */
    public static final ApplistImport APPLIST_IMPORT = ApplistImport.APPLIST_IMPORT;

    /**
     * The table <code>public.bandwidthshareinfo</code>.
     */
    public static final Bandwidthshareinfo BANDWIDTHSHAREINFO = Bandwidthshareinfo.BANDWIDTHSHAREINFO;

    /**
     * The table <code>public.bandwidthshareinfo_import</code>.
     */
    public static final BandwidthshareinfoImport BANDWIDTHSHAREINFO_IMPORT = BandwidthshareinfoImport.BANDWIDTHSHAREINFO_IMPORT;

    /**
     * The table <code>public.connectionpersimtime</code>.
     */
    public static final Connectionpersimtime CONNECTIONPERSIMTIME = Connectionpersimtime.CONNECTIONPERSIMTIME;

    /**
     * The table <code>public.connectionpersimtime_import</code>.
     */
    public static final ConnectionpersimtimeImport CONNECTIONPERSIMTIME_IMPORT = ConnectionpersimtimeImport.CONNECTIONPERSIMTIME_IMPORT;

    /**
     * The table <code>public.datacenterenergyconsumption</code>.
     */
    public static final Datacenterenergyconsumption DATACENTERENERGYCONSUMPTION = Datacenterenergyconsumption.DATACENTERENERGYCONSUMPTION;

    /**
     * The table <code>public.datacenterenergyconsumption_import</code>.
     */
    public static final DatacenterenergyconsumptionImport DATACENTERENERGYCONSUMPTION_IMPORT = DatacenterenergyconsumptionImport.DATACENTERENERGYCONSUMPTION_IMPORT;

    /**
     * The table <code>public.historyentry</code>.
     */
    public static final Historyentry HISTORYENTRY = Historyentry.HISTORYENTRY;

    /**
     * The table <code>public.historyentry_import</code>.
     */
    public static final HistoryentryImport HISTORYENTRY_IMPORT = HistoryentryImport.HISTORYENTRY_IMPORT;

    /**
     * The table <code>public.hostpowerconsumption</code>.
     */
    public static final Hostpowerconsumption HOSTPOWERCONSUMPTION = Hostpowerconsumption.HOSTPOWERCONSUMPTION;

    /**
     * The table <code>public.hostpowerconsumption_import</code>.
     */
    public static final HostpowerconsumptionImport HOSTPOWERCONSUMPTION_IMPORT = HostpowerconsumptionImport.HOSTPOWERCONSUMPTION_IMPORT;

    /**
     * The table <code>public.neighbourschange</code>.
     */
    public static final Neighbourschange NEIGHBOURSCHANGE = Neighbourschange.NEIGHBOURSCHANGE;

    /**
     * The table <code>public.osmoticappsstats</code>.
     */
    public static final Osmoticappsstats OSMOTICAPPSSTATS = Osmoticappsstats.OSMOTICAPPSSTATS;

    /**
     * The table <code>public.osmoticappsstats_import</code>.
     */
    public static final OsmoticappsstatsImport OSMOTICAPPSSTATS_IMPORT = OsmoticappsstatsImport.OSMOTICAPPSSTATS_IMPORT;

    /**
     * The table <code>public.overallappresults</code>.
     */
    public static final Overallappresults OVERALLAPPRESULTS = Overallappresults.OVERALLAPPRESULTS;

    /**
     * The table <code>public.overallappresults_import</code>.
     */
    public static final OverallappresultsImport OVERALLAPPRESULTS_IMPORT = OverallappresultsImport.OVERALLAPPRESULTS_IMPORT;

    /**
     * The table <code>public.powerutilisationhistory</code>.
     */
    public static final Powerutilisationhistory POWERUTILISATIONHISTORY = Powerutilisationhistory.POWERUTILISATIONHISTORY;

    /**
     * The table <code>public.powerutilisationhistory_import</code>.
     */
    public static final PowerutilisationhistoryImport POWERUTILISATIONHISTORY_IMPORT = PowerutilisationhistoryImport.POWERUTILISATIONHISTORY_IMPORT;

    /**
     * The table <code>public.rsuinformation</code>.
     */
    public static final Rsuinformation RSUINFORMATION = Rsuinformation.RSUINFORMATION;

    /**
     * The table <code>public.rsuinformation_import</code>.
     */
    public static final RsuinformationImport RSUINFORMATION_IMPORT = RsuinformationImport.RSUINFORMATION_IMPORT;

    /**
     * The table <code>public.sourcetodestlinks</code>.
     */
    public static final Sourcetodestlinks SOURCETODESTLINKS = Sourcetodestlinks.SOURCETODESTLINKS;

    /**
     * The table <code>public.switchpowerconsumption</code>.
     */
    public static final Switchpowerconsumption SWITCHPOWERCONSUMPTION = Switchpowerconsumption.SWITCHPOWERCONSUMPTION;

    /**
     * The table <code>public.switchpowerconsumption_import</code>.
     */
    public static final SwitchpowerconsumptionImport SWITCHPOWERCONSUMPTION_IMPORT = SwitchpowerconsumptionImport.SWITCHPOWERCONSUMPTION_IMPORT;

    /**
     * The table <code>public.timed_scc</code>.
     */
    public static final TimedScc TIMED_SCC = TimedScc.TIMED_SCC;

    /**
     * The table <code>public.vehinformation</code>.
     */
    public static final Vehinformation VEHINFORMATION = Vehinformation.VEHINFORMATION;

    /**
     * The table <code>public.vehinformation_import</code>.
     */
    public static final VehinformationImport VEHINFORMATION_IMPORT = VehinformationImport.VEHINFORMATION_IMPORT;
}
