/*
 * This file is generated by jOOQ.
 */
package uk.ncl.giacomobergami.utils.database.jooq.tables;


import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import uk.ncl.giacomobergami.utils.database.jooq.Public;
import uk.ncl.giacomobergami.utils.database.jooq.tables.records.AccuratebatteryinfoImportRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AccuratebatteryinfoImport extends TableImpl<AccuratebatteryinfoImportRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.accuratebatteryinfo_import</code>
     */
    public static final AccuratebatteryinfoImport ACCURATEBATTERYINFO_IMPORT = new AccuratebatteryinfoImport();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AccuratebatteryinfoImportRecord> getRecordType() {
        return AccuratebatteryinfoImportRecord.class;
    }

    /**
     * The column <code>public.accuratebatteryinfo_import.iotdevicename</code>.
     */
    public final TableField<AccuratebatteryinfoImportRecord, String> IOTDEVICENAME = createField(DSL.name("iotdevicename"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.accuratebatteryinfo_import.consumption</code>.
     */
    public final TableField<AccuratebatteryinfoImportRecord, Double> CONSUMPTION = createField(DSL.name("consumption"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>public.accuratebatteryinfo_import.flowid</code>.
     */
    public final TableField<AccuratebatteryinfoImportRecord, Integer> FLOWID = createField(DSL.name("flowid"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.accuratebatteryinfo_import.nopackets</code>.
     */
    public final TableField<AccuratebatteryinfoImportRecord, Double> NOPACKETS = createField(DSL.name("nopackets"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>public.accuratebatteryinfo_import.time</code>.
     */
    public final TableField<AccuratebatteryinfoImportRecord, Double> TIME = createField(DSL.name("time"), SQLDataType.DOUBLE.nullable(false), this, "");

    private AccuratebatteryinfoImport(Name alias, Table<AccuratebatteryinfoImportRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private AccuratebatteryinfoImport(Name alias, Table<AccuratebatteryinfoImportRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.accuratebatteryinfo_import</code> table
     * reference
     */
    public AccuratebatteryinfoImport(String alias) {
        this(DSL.name(alias), ACCURATEBATTERYINFO_IMPORT);
    }

    /**
     * Create an aliased <code>public.accuratebatteryinfo_import</code> table
     * reference
     */
    public AccuratebatteryinfoImport(Name alias) {
        this(alias, ACCURATEBATTERYINFO_IMPORT);
    }

    /**
     * Create a <code>public.accuratebatteryinfo_import</code> table reference
     */
    public AccuratebatteryinfoImport() {
        this(DSL.name("accuratebatteryinfo_import"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public AccuratebatteryinfoImport as(String alias) {
        return new AccuratebatteryinfoImport(DSL.name(alias), this);
    }

    @Override
    public AccuratebatteryinfoImport as(Name alias) {
        return new AccuratebatteryinfoImport(alias, this);
    }

    @Override
    public AccuratebatteryinfoImport as(Table<?> alias) {
        return new AccuratebatteryinfoImport(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AccuratebatteryinfoImport rename(String name) {
        return new AccuratebatteryinfoImport(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AccuratebatteryinfoImport rename(Name name) {
        return new AccuratebatteryinfoImport(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AccuratebatteryinfoImport rename(Table<?> name) {
        return new AccuratebatteryinfoImport(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AccuratebatteryinfoImport where(Condition condition) {
        return new AccuratebatteryinfoImport(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AccuratebatteryinfoImport where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AccuratebatteryinfoImport where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AccuratebatteryinfoImport where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AccuratebatteryinfoImport where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AccuratebatteryinfoImport where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AccuratebatteryinfoImport where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AccuratebatteryinfoImport where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AccuratebatteryinfoImport whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AccuratebatteryinfoImport whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
