/*
 * This file is generated by jOOQ.
 */
package uk.ncl.giacomobergami.utils.database.jooq.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import uk.ncl.giacomobergami.utils.database.jooq.Indexes;
import uk.ncl.giacomobergami.utils.database.jooq.Keys;
import uk.ncl.giacomobergami.utils.database.jooq.Public;
import uk.ncl.giacomobergami.utils.database.jooq.tables.records.AmbulanceinformationRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Ambulanceinformation extends TableImpl<AmbulanceinformationRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.ambulanceinformation</code>
     */
    public static final Ambulanceinformation AMBULANCEINFORMATION = new Ambulanceinformation();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AmbulanceinformationRecord> getRecordType() {
        return AmbulanceinformationRecord.class;
    }

    /**
     * The column <code>public.ambulanceinformation.di_entry_id</code>.
     */
    public final TableField<AmbulanceinformationRecord, Integer> DI_ENTRY_ID = createField(DSL.name("di_entry_id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.ambulanceinformation.vehicle_id</code>.
     */
    public final TableField<AmbulanceinformationRecord, String> VEHICLE_ID = createField(DSL.name("vehicle_id"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.ambulanceinformation.x</code>.
     */
    public final TableField<AmbulanceinformationRecord, Double> X = createField(DSL.name("x"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>public.ambulanceinformation.y</code>.
     */
    public final TableField<AmbulanceinformationRecord, Double> Y = createField(DSL.name("y"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>public.ambulanceinformation.angle</code>.
     */
    public final TableField<AmbulanceinformationRecord, Double> ANGLE = createField(DSL.name("angle"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>public.ambulanceinformation.vehicle_type</code>.
     */
    public final TableField<AmbulanceinformationRecord, String> VEHICLE_TYPE = createField(DSL.name("vehicle_type"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.ambulanceinformation.speed</code>.
     */
    public final TableField<AmbulanceinformationRecord, Double> SPEED = createField(DSL.name("speed"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>public.ambulanceinformation.pos</code>.
     */
    public final TableField<AmbulanceinformationRecord, Double> POS = createField(DSL.name("pos"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>public.ambulanceinformation.lane</code>.
     */
    public final TableField<AmbulanceinformationRecord, String> LANE = createField(DSL.name("lane"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.ambulanceinformation.slope</code>.
     */
    public final TableField<AmbulanceinformationRecord, Double> SLOPE = createField(DSL.name("slope"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>public.ambulanceinformation.simtime</code>.
     */
    public final TableField<AmbulanceinformationRecord, Double> SIMTIME = createField(DSL.name("simtime"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>public.ambulanceinformation.injected</code>.
     */
    public final TableField<AmbulanceinformationRecord, String> INJECTED = createField(DSL.name("injected"), SQLDataType.VARCHAR(5).nullable(false), this, "");

    private Ambulanceinformation(Name alias, Table<AmbulanceinformationRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Ambulanceinformation(Name alias, Table<AmbulanceinformationRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.ambulanceinformation</code> table
     * reference
     */
    public Ambulanceinformation(String alias) {
        this(DSL.name(alias), AMBULANCEINFORMATION);
    }

    /**
     * Create an aliased <code>public.ambulanceinformation</code> table
     * reference
     */
    public Ambulanceinformation(Name alias) {
        this(alias, AMBULANCEINFORMATION);
    }

    /**
     * Create a <code>public.ambulanceinformation</code> table reference
     */
    public Ambulanceinformation() {
        this(DSL.name("ambulanceinformation"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.AMBULANCEINDEX);
    }

    @Override
    public Identity<AmbulanceinformationRecord, Integer> getIdentity() {
        return (Identity<AmbulanceinformationRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<AmbulanceinformationRecord> getPrimaryKey() {
        return Keys.AMBULANCEINFORMATION_PKEY;
    }

    @Override
    public Ambulanceinformation as(String alias) {
        return new Ambulanceinformation(DSL.name(alias), this);
    }

    @Override
    public Ambulanceinformation as(Name alias) {
        return new Ambulanceinformation(alias, this);
    }

    @Override
    public Ambulanceinformation as(Table<?> alias) {
        return new Ambulanceinformation(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Ambulanceinformation rename(String name) {
        return new Ambulanceinformation(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Ambulanceinformation rename(Name name) {
        return new Ambulanceinformation(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Ambulanceinformation rename(Table<?> name) {
        return new Ambulanceinformation(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Ambulanceinformation where(Condition condition) {
        return new Ambulanceinformation(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Ambulanceinformation where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Ambulanceinformation where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Ambulanceinformation where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Ambulanceinformation where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Ambulanceinformation where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Ambulanceinformation where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Ambulanceinformation where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Ambulanceinformation whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Ambulanceinformation whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
