/*
 * This file is generated by jOOQ.
 */
package uk.ncl.giacomobergami.utils.database.jooq.tables;


import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import uk.ncl.giacomobergami.utils.database.jooq.Public;
import uk.ncl.giacomobergami.utils.database.jooq.tables.records.AmbulanceinformationImportRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AmbulanceinformationImport extends TableImpl<AmbulanceinformationImportRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.ambulanceinformation_import</code>
     */
    public static final AmbulanceinformationImport AMBULANCEINFORMATION_IMPORT = new AmbulanceinformationImport();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AmbulanceinformationImportRecord> getRecordType() {
        return AmbulanceinformationImportRecord.class;
    }

    /**
     * The column <code>public.ambulanceinformation_import.vehicle_id</code>.
     */
    public final TableField<AmbulanceinformationImportRecord, String> VEHICLE_ID = createField(DSL.name("vehicle_id"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.ambulanceinformation_import.x</code>.
     */
    public final TableField<AmbulanceinformationImportRecord, Double> X = createField(DSL.name("x"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>public.ambulanceinformation_import.y</code>.
     */
    public final TableField<AmbulanceinformationImportRecord, Double> Y = createField(DSL.name("y"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>public.ambulanceinformation_import.angle</code>.
     */
    public final TableField<AmbulanceinformationImportRecord, Double> ANGLE = createField(DSL.name("angle"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>public.ambulanceinformation_import.vehicle_type</code>.
     */
    public final TableField<AmbulanceinformationImportRecord, String> VEHICLE_TYPE = createField(DSL.name("vehicle_type"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.ambulanceinformation_import.speed</code>.
     */
    public final TableField<AmbulanceinformationImportRecord, Double> SPEED = createField(DSL.name("speed"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>public.ambulanceinformation_import.pos</code>.
     */
    public final TableField<AmbulanceinformationImportRecord, Double> POS = createField(DSL.name("pos"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>public.ambulanceinformation_import.lane</code>.
     */
    public final TableField<AmbulanceinformationImportRecord, String> LANE = createField(DSL.name("lane"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.ambulanceinformation_import.slope</code>.
     */
    public final TableField<AmbulanceinformationImportRecord, Double> SLOPE = createField(DSL.name("slope"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>public.ambulanceinformation_import.simtime</code>.
     */
    public final TableField<AmbulanceinformationImportRecord, Double> SIMTIME = createField(DSL.name("simtime"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>public.ambulanceinformation_import.injected</code>.
     */
    public final TableField<AmbulanceinformationImportRecord, String> INJECTED = createField(DSL.name("injected"), SQLDataType.VARCHAR(5).nullable(false), this, "");

    private AmbulanceinformationImport(Name alias, Table<AmbulanceinformationImportRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private AmbulanceinformationImport(Name alias, Table<AmbulanceinformationImportRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.ambulanceinformation_import</code> table
     * reference
     */
    public AmbulanceinformationImport(String alias) {
        this(DSL.name(alias), AMBULANCEINFORMATION_IMPORT);
    }

    /**
     * Create an aliased <code>public.ambulanceinformation_import</code> table
     * reference
     */
    public AmbulanceinformationImport(Name alias) {
        this(alias, AMBULANCEINFORMATION_IMPORT);
    }

    /**
     * Create a <code>public.ambulanceinformation_import</code> table reference
     */
    public AmbulanceinformationImport() {
        this(DSL.name("ambulanceinformation_import"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public AmbulanceinformationImport as(String alias) {
        return new AmbulanceinformationImport(DSL.name(alias), this);
    }

    @Override
    public AmbulanceinformationImport as(Name alias) {
        return new AmbulanceinformationImport(alias, this);
    }

    @Override
    public AmbulanceinformationImport as(Table<?> alias) {
        return new AmbulanceinformationImport(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AmbulanceinformationImport rename(String name) {
        return new AmbulanceinformationImport(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AmbulanceinformationImport rename(Name name) {
        return new AmbulanceinformationImport(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AmbulanceinformationImport rename(Table<?> name) {
        return new AmbulanceinformationImport(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AmbulanceinformationImport where(Condition condition) {
        return new AmbulanceinformationImport(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AmbulanceinformationImport where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AmbulanceinformationImport where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AmbulanceinformationImport where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AmbulanceinformationImport where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AmbulanceinformationImport where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AmbulanceinformationImport where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AmbulanceinformationImport where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AmbulanceinformationImport whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AmbulanceinformationImport whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
