/*
 * This file is generated by jOOQ.
 */
package uk.ncl.giacomobergami.utils.database.jooq.tables;


import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import uk.ncl.giacomobergami.utils.database.jooq.Public;
import uk.ncl.giacomobergami.utils.database.jooq.tables.records.ApplistImportRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ApplistImport extends TableImpl<ApplistImportRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.applist_import</code>
     */
    public static final ApplistImport APPLIST_IMPORT = new ApplistImport();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ApplistImportRecord> getRecordType() {
        return ApplistImportRecord.class;
    }

    /**
     * The column <code>public.applist_import.appid</code>.
     */
    public final TableField<ApplistImportRecord, Integer> APPID = createField(DSL.name("appid"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.applist_import.appname</code>.
     */
    public final TableField<ApplistImportRecord, String> APPNAME = createField(DSL.name("appname"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.applist_import.appstarttime</code>.
     */
    public final TableField<ApplistImportRecord, Double> APPSTARTTIME = createField(DSL.name("appstarttime"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>public.applist_import.clouddatacentername</code>.
     */
    public final TableField<ApplistImportRecord, String> CLOUDDATACENTERNAME = createField(DSL.name("clouddatacentername"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.applist_import.clouddcid</code>.
     */
    public final TableField<ApplistImportRecord, Integer> CLOUDDCID = createField(DSL.name("clouddcid"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.applist_import.datarate</code>.
     */
    public final TableField<ApplistImportRecord, Double> DATARATE = createField(DSL.name("datarate"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>public.applist_import.edgedatacentername</code>.
     */
    public final TableField<ApplistImportRecord, String> EDGEDATACENTERNAME = createField(DSL.name("edgedatacentername"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public.applist_import.edgedcid</code>.
     */
    public final TableField<ApplistImportRecord, Integer> EDGEDCID = createField(DSL.name("edgedcid"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.applist_import.endtime</code>.
     */
    public final TableField<ApplistImportRecord, Double> ENDTIME = createField(DSL.name("endtime"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column
     * <code>public.applist_import.iotdevicebatteryconsumption</code>.
     */
    public final TableField<ApplistImportRecord, Double> IOTDEVICEBATTERYCONSUMPTION = createField(DSL.name("iotdevicebatteryconsumption"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>public.applist_import.iotdevicebatterystatus</code>.
     */
    public final TableField<ApplistImportRecord, String> IOTDEVICEBATTERYSTATUS = createField(DSL.name("iotdevicebatterystatus"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.applist_import.iotdeviceid</code>.
     */
    public final TableField<ApplistImportRecord, Integer> IOTDEVICEID = createField(DSL.name("iotdeviceid"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.applist_import.iotdevicename</code>.
     */
    public final TableField<ApplistImportRecord, String> IOTDEVICENAME = createField(DSL.name("iotdevicename"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.applist_import.iotdeviceoutputsize</code>.
     */
    public final TableField<ApplistImportRecord, Integer> IOTDEVICEOUTPUTSIZE = createField(DSL.name("iotdeviceoutputsize"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.applist_import.isiotdevicedied</code>.
     */
    public final TableField<ApplistImportRecord, String> ISIOTDEVICEDIED = createField(DSL.name("isiotdevicedied"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.applist_import.melid</code>.
     */
    public final TableField<ApplistImportRecord, Integer> MELID = createField(DSL.name("melid"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.applist_import.melname</code>.
     */
    public final TableField<ApplistImportRecord, String> MELNAME = createField(DSL.name("melname"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.applist_import.meloutputsize</code>.
     */
    public final TableField<ApplistImportRecord, Integer> MELOUTPUTSIZE = createField(DSL.name("meloutputsize"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.applist_import.osmesiscloudletsize</code>.
     */
    public final TableField<ApplistImportRecord, Integer> OSMESISCLOUDLETSIZE = createField(DSL.name("osmesiscloudletsize"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.applist_import.osmesisedgeletsize</code>.
     */
    public final TableField<ApplistImportRecord, Integer> OSMESISEDGELETSIZE = createField(DSL.name("osmesisedgeletsize"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.applist_import.startdatagenerationtime</code>.
     */
    public final TableField<ApplistImportRecord, Double> STARTDATAGENERATIONTIME = createField(DSL.name("startdatagenerationtime"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>public.applist_import.stopdatagenerationtime</code>.
     */
    public final TableField<ApplistImportRecord, Double> STOPDATAGENERATIONTIME = createField(DSL.name("stopdatagenerationtime"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>public.applist_import.vmcloudid</code>.
     */
    public final TableField<ApplistImportRecord, Integer> VMCLOUDID = createField(DSL.name("vmcloudid"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.applist_import.vmname</code>.
     */
    public final TableField<ApplistImportRecord, String> VMNAME = createField(DSL.name("vmname"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.applist_import.workflowid</code>.
     */
    public final TableField<ApplistImportRecord, Integer> WORKFLOWID = createField(DSL.name("workflowid"), SQLDataType.INTEGER.nullable(false), this, "");

    private ApplistImport(Name alias, Table<ApplistImportRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ApplistImport(Name alias, Table<ApplistImportRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.applist_import</code> table reference
     */
    public ApplistImport(String alias) {
        this(DSL.name(alias), APPLIST_IMPORT);
    }

    /**
     * Create an aliased <code>public.applist_import</code> table reference
     */
    public ApplistImport(Name alias) {
        this(alias, APPLIST_IMPORT);
    }

    /**
     * Create a <code>public.applist_import</code> table reference
     */
    public ApplistImport() {
        this(DSL.name("applist_import"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public ApplistImport as(String alias) {
        return new ApplistImport(DSL.name(alias), this);
    }

    @Override
    public ApplistImport as(Name alias) {
        return new ApplistImport(alias, this);
    }

    @Override
    public ApplistImport as(Table<?> alias) {
        return new ApplistImport(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ApplistImport rename(String name) {
        return new ApplistImport(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ApplistImport rename(Name name) {
        return new ApplistImport(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ApplistImport rename(Table<?> name) {
        return new ApplistImport(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ApplistImport where(Condition condition) {
        return new ApplistImport(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ApplistImport where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ApplistImport where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ApplistImport where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ApplistImport where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ApplistImport where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ApplistImport where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ApplistImport where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ApplistImport whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ApplistImport whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
