/*
 * This file is generated by jOOQ.
 */
package uk.ncl.giacomobergami.utils.database.jooq.tables;


import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import uk.ncl.giacomobergami.utils.database.jooq.Public;
import uk.ncl.giacomobergami.utils.database.jooq.tables.records.BandwidthshareinfoImportRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class BandwidthshareinfoImport extends TableImpl<BandwidthshareinfoImportRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.bandwidthshareinfo_import</code>
     */
    public static final BandwidthshareinfoImport BANDWIDTHSHAREINFO_IMPORT = new BandwidthshareinfoImport();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BandwidthshareinfoImportRecord> getRecordType() {
        return BandwidthshareinfoImportRecord.class;
    }

    /**
     * The column <code>public.bandwidthshareinfo_import.bandwidthshare</code>.
     */
    public final TableField<BandwidthshareinfoImportRecord, Double> BANDWIDTHSHARE = createField(DSL.name("bandwidthshare"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>public.bandwidthshareinfo_import.channelid</code>.
     */
    public final TableField<BandwidthshareinfoImportRecord, String> CHANNELID = createField(DSL.name("channelid"), SQLDataType.VARCHAR(60).nullable(false), this, "");

    /**
     * The column <code>public.bandwidthshareinfo_import.edgename</code>.
     */
    public final TableField<BandwidthshareinfoImportRecord, String> EDGENAME = createField(DSL.name("edgename"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.bandwidthshareinfo_import.melname</code>.
     */
    public final TableField<BandwidthshareinfoImportRecord, String> MELNAME = createField(DSL.name("melname"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.bandwidthshareinfo_import.timestamp</code>.
     */
    public final TableField<BandwidthshareinfoImportRecord, Double> TIMESTAMP = createField(DSL.name("timestamp"), SQLDataType.DOUBLE.nullable(false), this, "");

    private BandwidthshareinfoImport(Name alias, Table<BandwidthshareinfoImportRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private BandwidthshareinfoImport(Name alias, Table<BandwidthshareinfoImportRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.bandwidthshareinfo_import</code> table
     * reference
     */
    public BandwidthshareinfoImport(String alias) {
        this(DSL.name(alias), BANDWIDTHSHAREINFO_IMPORT);
    }

    /**
     * Create an aliased <code>public.bandwidthshareinfo_import</code> table
     * reference
     */
    public BandwidthshareinfoImport(Name alias) {
        this(alias, BANDWIDTHSHAREINFO_IMPORT);
    }

    /**
     * Create a <code>public.bandwidthshareinfo_import</code> table reference
     */
    public BandwidthshareinfoImport() {
        this(DSL.name("bandwidthshareinfo_import"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public BandwidthshareinfoImport as(String alias) {
        return new BandwidthshareinfoImport(DSL.name(alias), this);
    }

    @Override
    public BandwidthshareinfoImport as(Name alias) {
        return new BandwidthshareinfoImport(alias, this);
    }

    @Override
    public BandwidthshareinfoImport as(Table<?> alias) {
        return new BandwidthshareinfoImport(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public BandwidthshareinfoImport rename(String name) {
        return new BandwidthshareinfoImport(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public BandwidthshareinfoImport rename(Name name) {
        return new BandwidthshareinfoImport(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public BandwidthshareinfoImport rename(Table<?> name) {
        return new BandwidthshareinfoImport(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BandwidthshareinfoImport where(Condition condition) {
        return new BandwidthshareinfoImport(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BandwidthshareinfoImport where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BandwidthshareinfoImport where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BandwidthshareinfoImport where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BandwidthshareinfoImport where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BandwidthshareinfoImport where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BandwidthshareinfoImport where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BandwidthshareinfoImport where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BandwidthshareinfoImport whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BandwidthshareinfoImport whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
