/*
 * This file is generated by jOOQ.
 */
package uk.ncl.giacomobergami.utils.database.jooq.tables;


import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import uk.ncl.giacomobergami.utils.database.jooq.Public;
import uk.ncl.giacomobergami.utils.database.jooq.tables.records.ConnectionpersimtimeImportRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ConnectionpersimtimeImport extends TableImpl<ConnectionpersimtimeImportRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.connectionpersimtime_import</code>
     */
    public static final ConnectionpersimtimeImport CONNECTIONPERSIMTIME_IMPORT = new ConnectionpersimtimeImport();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ConnectionpersimtimeImportRecord> getRecordType() {
        return ConnectionpersimtimeImportRecord.class;
    }

    /**
     * The column <code>public.connectionpersimtime_import.iotdevices</code>.
     */
    public final TableField<ConnectionpersimtimeImportRecord, Integer> IOTDEVICES = createField(DSL.name("iotdevices"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.connectionpersimtime_import.edgehost</code>.
     */
    public final TableField<ConnectionpersimtimeImportRecord, String> EDGEHOST = createField(DSL.name("edgehost"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.connectionpersimtime_import.cps_time</code>.
     */
    public final TableField<ConnectionpersimtimeImportRecord, Double> CPS_TIME = createField(DSL.name("cps_time"), SQLDataType.DOUBLE.nullable(false), this, "");

    private ConnectionpersimtimeImport(Name alias, Table<ConnectionpersimtimeImportRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ConnectionpersimtimeImport(Name alias, Table<ConnectionpersimtimeImportRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.connectionpersimtime_import</code> table
     * reference
     */
    public ConnectionpersimtimeImport(String alias) {
        this(DSL.name(alias), CONNECTIONPERSIMTIME_IMPORT);
    }

    /**
     * Create an aliased <code>public.connectionpersimtime_import</code> table
     * reference
     */
    public ConnectionpersimtimeImport(Name alias) {
        this(alias, CONNECTIONPERSIMTIME_IMPORT);
    }

    /**
     * Create a <code>public.connectionpersimtime_import</code> table reference
     */
    public ConnectionpersimtimeImport() {
        this(DSL.name("connectionpersimtime_import"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public ConnectionpersimtimeImport as(String alias) {
        return new ConnectionpersimtimeImport(DSL.name(alias), this);
    }

    @Override
    public ConnectionpersimtimeImport as(Name alias) {
        return new ConnectionpersimtimeImport(alias, this);
    }

    @Override
    public ConnectionpersimtimeImport as(Table<?> alias) {
        return new ConnectionpersimtimeImport(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ConnectionpersimtimeImport rename(String name) {
        return new ConnectionpersimtimeImport(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ConnectionpersimtimeImport rename(Name name) {
        return new ConnectionpersimtimeImport(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ConnectionpersimtimeImport rename(Table<?> name) {
        return new ConnectionpersimtimeImport(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ConnectionpersimtimeImport where(Condition condition) {
        return new ConnectionpersimtimeImport(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ConnectionpersimtimeImport where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ConnectionpersimtimeImport where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ConnectionpersimtimeImport where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ConnectionpersimtimeImport where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ConnectionpersimtimeImport where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ConnectionpersimtimeImport where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ConnectionpersimtimeImport where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ConnectionpersimtimeImport whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ConnectionpersimtimeImport whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
