/*
 * This file is generated by jOOQ.
 */
package uk.ncl.giacomobergami.utils.database.jooq.tables;


import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import uk.ncl.giacomobergami.utils.database.jooq.Public;
import uk.ncl.giacomobergami.utils.database.jooq.tables.records.DatacenterenergyconsumptionImportRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DatacenterenergyconsumptionImport extends TableImpl<DatacenterenergyconsumptionImportRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of
     * <code>public.datacenterenergyconsumption_import</code>
     */
    public static final DatacenterenergyconsumptionImport DATACENTERENERGYCONSUMPTION_IMPORT = new DatacenterenergyconsumptionImport();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DatacenterenergyconsumptionImportRecord> getRecordType() {
        return DatacenterenergyconsumptionImportRecord.class;
    }

    /**
     * The column
     * <code>public.datacenterenergyconsumption_import.hostenergyconsumed</code>.
     */
    public final TableField<DatacenterenergyconsumptionImportRecord, Double> HOSTENERGYCONSUMED = createField(DSL.name("hostenergyconsumed"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column
     * <code>public.datacenterenergyconsumption_import.switchenergyconsumed</code>.
     */
    public final TableField<DatacenterenergyconsumptionImportRecord, Double> SWITCHENERGYCONSUMED = createField(DSL.name("switchenergyconsumed"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column
     * <code>public.datacenterenergyconsumption_import.totalenergyconsumed</code>.
     */
    public final TableField<DatacenterenergyconsumptionImportRecord, Double> TOTALENERGYCONSUMED = createField(DSL.name("totalenergyconsumed"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>public.datacenterenergyconsumption_import.dcname</code>.
     */
    public final TableField<DatacenterenergyconsumptionImportRecord, String> DCNAME = createField(DSL.name("dcname"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column
     * <code>public.datacenterenergyconsumption_import.finishtime</code>.
     */
    public final TableField<DatacenterenergyconsumptionImportRecord, Double> FINISHTIME = createField(DSL.name("finishtime"), SQLDataType.DOUBLE.nullable(false), this, "");

    private DatacenterenergyconsumptionImport(Name alias, Table<DatacenterenergyconsumptionImportRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private DatacenterenergyconsumptionImport(Name alias, Table<DatacenterenergyconsumptionImportRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.datacenterenergyconsumption_import</code>
     * table reference
     */
    public DatacenterenergyconsumptionImport(String alias) {
        this(DSL.name(alias), DATACENTERENERGYCONSUMPTION_IMPORT);
    }

    /**
     * Create an aliased <code>public.datacenterenergyconsumption_import</code>
     * table reference
     */
    public DatacenterenergyconsumptionImport(Name alias) {
        this(alias, DATACENTERENERGYCONSUMPTION_IMPORT);
    }

    /**
     * Create a <code>public.datacenterenergyconsumption_import</code> table
     * reference
     */
    public DatacenterenergyconsumptionImport() {
        this(DSL.name("datacenterenergyconsumption_import"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public DatacenterenergyconsumptionImport as(String alias) {
        return new DatacenterenergyconsumptionImport(DSL.name(alias), this);
    }

    @Override
    public DatacenterenergyconsumptionImport as(Name alias) {
        return new DatacenterenergyconsumptionImport(alias, this);
    }

    @Override
    public DatacenterenergyconsumptionImport as(Table<?> alias) {
        return new DatacenterenergyconsumptionImport(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public DatacenterenergyconsumptionImport rename(String name) {
        return new DatacenterenergyconsumptionImport(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DatacenterenergyconsumptionImport rename(Name name) {
        return new DatacenterenergyconsumptionImport(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public DatacenterenergyconsumptionImport rename(Table<?> name) {
        return new DatacenterenergyconsumptionImport(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DatacenterenergyconsumptionImport where(Condition condition) {
        return new DatacenterenergyconsumptionImport(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DatacenterenergyconsumptionImport where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DatacenterenergyconsumptionImport where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DatacenterenergyconsumptionImport where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DatacenterenergyconsumptionImport where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DatacenterenergyconsumptionImport where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DatacenterenergyconsumptionImport where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DatacenterenergyconsumptionImport where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DatacenterenergyconsumptionImport whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DatacenterenergyconsumptionImport whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
