/*
 * This file is generated by jOOQ.
 */
package uk.ncl.giacomobergami.utils.database.jooq.tables;


import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import uk.ncl.giacomobergami.utils.database.jooq.Public;
import uk.ncl.giacomobergami.utils.database.jooq.tables.records.HistoryentryImportRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class HistoryentryImport extends TableImpl<HistoryentryImportRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.historyentry_import</code>
     */
    public static final HistoryentryImport HISTORYENTRY_IMPORT = new HistoryentryImport();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<HistoryentryImportRecord> getRecordType() {
        return HistoryentryImportRecord.class;
    }

    /**
     * The column <code>public.historyentry_import.numactiveports</code>.
     */
    public final TableField<HistoryentryImportRecord, Integer> NUMACTIVEPORTS = createField(DSL.name("numactiveports"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.historyentry_import.starttime</code>.
     */
    public final TableField<HistoryentryImportRecord, Double> STARTTIME = createField(DSL.name("starttime"), SQLDataType.DOUBLE, this, "");

    private HistoryentryImport(Name alias, Table<HistoryentryImportRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private HistoryentryImport(Name alias, Table<HistoryentryImportRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.historyentry_import</code> table reference
     */
    public HistoryentryImport(String alias) {
        this(DSL.name(alias), HISTORYENTRY_IMPORT);
    }

    /**
     * Create an aliased <code>public.historyentry_import</code> table reference
     */
    public HistoryentryImport(Name alias) {
        this(alias, HISTORYENTRY_IMPORT);
    }

    /**
     * Create a <code>public.historyentry_import</code> table reference
     */
    public HistoryentryImport() {
        this(DSL.name("historyentry_import"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public HistoryentryImport as(String alias) {
        return new HistoryentryImport(DSL.name(alias), this);
    }

    @Override
    public HistoryentryImport as(Name alias) {
        return new HistoryentryImport(alias, this);
    }

    @Override
    public HistoryentryImport as(Table<?> alias) {
        return new HistoryentryImport(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public HistoryentryImport rename(String name) {
        return new HistoryentryImport(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public HistoryentryImport rename(Name name) {
        return new HistoryentryImport(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public HistoryentryImport rename(Table<?> name) {
        return new HistoryentryImport(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public HistoryentryImport where(Condition condition) {
        return new HistoryentryImport(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public HistoryentryImport where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public HistoryentryImport where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public HistoryentryImport where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public HistoryentryImport where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public HistoryentryImport where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public HistoryentryImport where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public HistoryentryImport where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public HistoryentryImport whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public HistoryentryImport whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
