/*
 * This file is generated by jOOQ.
 */
package uk.ncl.giacomobergami.utils.database.jooq.tables;


import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import uk.ncl.giacomobergami.utils.database.jooq.Public;
import uk.ncl.giacomobergami.utils.database.jooq.tables.records.HostpowerconsumptionImportRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class HostpowerconsumptionImport extends TableImpl<HostpowerconsumptionImportRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.hostpowerconsumption_import</code>
     */
    public static final HostpowerconsumptionImport HOSTPOWERCONSUMPTION_IMPORT = new HostpowerconsumptionImport();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<HostpowerconsumptionImportRecord> getRecordType() {
        return HostpowerconsumptionImportRecord.class;
    }

    /**
     * The column <code>public.hostpowerconsumption_import.dcname</code>.
     */
    public final TableField<HostpowerconsumptionImportRecord, String> DCNAME = createField(DSL.name("dcname"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.hostpowerconsumption_import.energy</code>.
     */
    public final TableField<HostpowerconsumptionImportRecord, Double> ENERGY = createField(DSL.name("energy"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>public.hostpowerconsumption_import.hpc_name</code>.
     */
    public final TableField<HostpowerconsumptionImportRecord, String> HPC_NAME = createField(DSL.name("hpc_name"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    private HostpowerconsumptionImport(Name alias, Table<HostpowerconsumptionImportRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private HostpowerconsumptionImport(Name alias, Table<HostpowerconsumptionImportRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.hostpowerconsumption_import</code> table
     * reference
     */
    public HostpowerconsumptionImport(String alias) {
        this(DSL.name(alias), HOSTPOWERCONSUMPTION_IMPORT);
    }

    /**
     * Create an aliased <code>public.hostpowerconsumption_import</code> table
     * reference
     */
    public HostpowerconsumptionImport(Name alias) {
        this(alias, HOSTPOWERCONSUMPTION_IMPORT);
    }

    /**
     * Create a <code>public.hostpowerconsumption_import</code> table reference
     */
    public HostpowerconsumptionImport() {
        this(DSL.name("hostpowerconsumption_import"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public HostpowerconsumptionImport as(String alias) {
        return new HostpowerconsumptionImport(DSL.name(alias), this);
    }

    @Override
    public HostpowerconsumptionImport as(Name alias) {
        return new HostpowerconsumptionImport(alias, this);
    }

    @Override
    public HostpowerconsumptionImport as(Table<?> alias) {
        return new HostpowerconsumptionImport(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public HostpowerconsumptionImport rename(String name) {
        return new HostpowerconsumptionImport(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public HostpowerconsumptionImport rename(Name name) {
        return new HostpowerconsumptionImport(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public HostpowerconsumptionImport rename(Table<?> name) {
        return new HostpowerconsumptionImport(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public HostpowerconsumptionImport where(Condition condition) {
        return new HostpowerconsumptionImport(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public HostpowerconsumptionImport where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public HostpowerconsumptionImport where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public HostpowerconsumptionImport where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public HostpowerconsumptionImport where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public HostpowerconsumptionImport where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public HostpowerconsumptionImport where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public HostpowerconsumptionImport where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public HostpowerconsumptionImport whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public HostpowerconsumptionImport whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
