/*
 * This file is generated by jOOQ.
 */
package uk.ncl.giacomobergami.utils.database.jooq.tables;


import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import uk.ncl.giacomobergami.utils.database.jooq.Public;
import uk.ncl.giacomobergami.utils.database.jooq.tables.records.OsmoticappsstatsImportRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class OsmoticappsstatsImport extends TableImpl<OsmoticappsstatsImportRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.osmoticappsstats_import</code>
     */
    public static final OsmoticappsstatsImport OSMOTICAPPSSTATS_IMPORT = new OsmoticappsstatsImport();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OsmoticappsstatsImportRecord> getRecordType() {
        return OsmoticappsstatsImportRecord.class;
    }

    /**
     * The column <code>public.osmoticappsstats_import.appid</code>.
     */
    public final TableField<OsmoticappsstatsImportRecord, Integer> APPID = createField(DSL.name("appid"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.osmoticappsstats_import.appname</code>.
     */
    public final TableField<OsmoticappsstatsImportRecord, String> APPNAME = createField(DSL.name("appname"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.osmoticappsstats_import.cloudletmisize</code>.
     */
    public final TableField<OsmoticappsstatsImportRecord, Double> CLOUDLETMISIZE = createField(DSL.name("cloudletmisize"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column
     * <code>public.osmoticappsstats_import.cloudletprocessingtimebyvm</code>.
     */
    public final TableField<OsmoticappsstatsImportRecord, Double> CLOUDLETPROCESSINGTIMEBYVM = createField(DSL.name("cloudletprocessingtimebyvm"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column
     * <code>public.osmoticappsstats_import.datasizeiotdevicetomel_mb</code>.
     */
    public final TableField<OsmoticappsstatsImportRecord, Integer> DATASIZEIOTDEVICETOMEL_MB = createField(DSL.name("datasizeiotdevicetomel_mb"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column
     * <code>public.osmoticappsstats_import.datasizemeltovm_mb</code>.
     */
    public final TableField<OsmoticappsstatsImportRecord, Integer> DATASIZEMELTOVM_MB = createField(DSL.name("datasizemeltovm_mb"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.osmoticappsstats_import.destinationvmname</code>.
     */
    public final TableField<OsmoticappsstatsImportRecord, String> DESTINATIONVMNAME = createField(DSL.name("destinationvmname"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.osmoticappsstats_import.edgeletmisize</code>.
     */
    public final TableField<OsmoticappsstatsImportRecord, Double> EDGELETMISIZE = createField(DSL.name("edgeletmisize"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column
     * <code>public.osmoticappsstats_import.edgeletprocessingtimebymel</code>.
     */
    public final TableField<OsmoticappsstatsImportRecord, Double> EDGELETPROCESSINGTIMEBYMEL = createField(DSL.name("edgeletprocessingtimebymel"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column
     * <code>public.osmoticappsstats_import.edgelet_mel_finishtime</code>.
     */
    public final TableField<OsmoticappsstatsImportRecord, Double> EDGELET_MEL_FINISHTIME = createField(DSL.name("edgelet_mel_finishtime"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column
     * <code>public.osmoticappsstats_import.edgelet_mel_starttime</code>.
     */
    public final TableField<OsmoticappsstatsImportRecord, Double> EDGELET_MEL_STARTTIME = createField(DSL.name("edgelet_mel_starttime"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>public.osmoticappsstats_import.finishtime</code>.
     */
    public final TableField<OsmoticappsstatsImportRecord, Double> FINISHTIME = createField(DSL.name("finishtime"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>public.osmoticappsstats_import.iotdevicename</code>.
     */
    public final TableField<OsmoticappsstatsImportRecord, String> IOTDEVICENAME = createField(DSL.name("iotdevicename"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.osmoticappsstats_import.melname</code>.
     */
    public final TableField<OsmoticappsstatsImportRecord, String> MELNAME = createField(DSL.name("melname"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column
     * <code>public.osmoticappsstats_import.melendtransmissiontime</code>.
     */
    public final TableField<OsmoticappsstatsImportRecord, Double> MELENDTRANSMISSIONTIME = createField(DSL.name("melendtransmissiontime"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column
     * <code>public.osmoticappsstats_import.melstarttransmissiontime</code>.
     */
    public final TableField<OsmoticappsstatsImportRecord, Double> MELSTARTTRANSMISSIONTIME = createField(DSL.name("melstarttransmissiontime"), SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>public.osmoticappsstats_import.starttime</code>.
     */
    public final TableField<OsmoticappsstatsImportRecord, Double> STARTTIME = createField(DSL.name("starttime"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>public.osmoticappsstats_import.oas_transaction</code>.
     */
    public final TableField<OsmoticappsstatsImportRecord, Integer> OAS_TRANSACTION = createField(DSL.name("oas_transaction"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column
     * <code>public.osmoticappsstats_import.transactiontotaltime</code>.
     */
    public final TableField<OsmoticappsstatsImportRecord, Double> TRANSACTIONTOTALTIME = createField(DSL.name("transactiontotaltime"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column
     * <code>public.osmoticappsstats_import.transmissiontimeiotdevicetomel</code>.
     */
    public final TableField<OsmoticappsstatsImportRecord, Double> TRANSMISSIONTIMEIOTDEVICETOMEL = createField(DSL.name("transmissiontimeiotdevicetomel"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column
     * <code>public.osmoticappsstats_import.transmissiontimemeltovm</code>.
     */
    public final TableField<OsmoticappsstatsImportRecord, Double> TRANSMISSIONTIMEMELTOVM = createField(DSL.name("transmissiontimemeltovm"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>public.osmoticappsstats_import.flowiotmelappid</code>.
     */
    public final TableField<OsmoticappsstatsImportRecord, Integer> FLOWIOTMELAPPID = createField(DSL.name("flowiotmelappid"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.osmoticappsstats_import.flowmelcloudappid</code>.
     */
    public final TableField<OsmoticappsstatsImportRecord, Integer> FLOWMELCLOUDAPPID = createField(DSL.name("flowmelcloudappid"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.osmoticappsstats_import.path_dst</code>.
     */
    public final TableField<OsmoticappsstatsImportRecord, String> PATH_DST = createField(DSL.name("path_dst"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.osmoticappsstats_import.path_src</code>.
     */
    public final TableField<OsmoticappsstatsImportRecord, String> PATH_SRC = createField(DSL.name("path_src"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.osmoticappsstats_import.edgetowanbw</code>.
     */
    public final TableField<OsmoticappsstatsImportRecord, Double> EDGETOWANBW = createField(DSL.name("edgetowanbw"), SQLDataType.DOUBLE.nullable(false), this, "");

    private OsmoticappsstatsImport(Name alias, Table<OsmoticappsstatsImportRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private OsmoticappsstatsImport(Name alias, Table<OsmoticappsstatsImportRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.osmoticappsstats_import</code> table
     * reference
     */
    public OsmoticappsstatsImport(String alias) {
        this(DSL.name(alias), OSMOTICAPPSSTATS_IMPORT);
    }

    /**
     * Create an aliased <code>public.osmoticappsstats_import</code> table
     * reference
     */
    public OsmoticappsstatsImport(Name alias) {
        this(alias, OSMOTICAPPSSTATS_IMPORT);
    }

    /**
     * Create a <code>public.osmoticappsstats_import</code> table reference
     */
    public OsmoticappsstatsImport() {
        this(DSL.name("osmoticappsstats_import"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public OsmoticappsstatsImport as(String alias) {
        return new OsmoticappsstatsImport(DSL.name(alias), this);
    }

    @Override
    public OsmoticappsstatsImport as(Name alias) {
        return new OsmoticappsstatsImport(alias, this);
    }

    @Override
    public OsmoticappsstatsImport as(Table<?> alias) {
        return new OsmoticappsstatsImport(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public OsmoticappsstatsImport rename(String name) {
        return new OsmoticappsstatsImport(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public OsmoticappsstatsImport rename(Name name) {
        return new OsmoticappsstatsImport(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public OsmoticappsstatsImport rename(Table<?> name) {
        return new OsmoticappsstatsImport(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OsmoticappsstatsImport where(Condition condition) {
        return new OsmoticappsstatsImport(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OsmoticappsstatsImport where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OsmoticappsstatsImport where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OsmoticappsstatsImport where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OsmoticappsstatsImport where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OsmoticappsstatsImport where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OsmoticappsstatsImport where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OsmoticappsstatsImport where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OsmoticappsstatsImport whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OsmoticappsstatsImport whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
