/*
 * This file is generated by jOOQ.
 */
package uk.ncl.giacomobergami.utils.database.jooq.tables;


import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import uk.ncl.giacomobergami.utils.database.jooq.Public;
import uk.ncl.giacomobergami.utils.database.jooq.tables.records.OverallappresultsImportRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class OverallappresultsImport extends TableImpl<OverallappresultsImportRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.overallappresults_import</code>
     */
    public static final OverallappresultsImport OVERALLAPPRESULTS_IMPORT = new OverallappresultsImport();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OverallappresultsImportRecord> getRecordType() {
        return OverallappresultsImportRecord.class;
    }

    /**
     * The column <code>public.overallappresults_import.appname</code>.
     */
    public final TableField<OverallappresultsImportRecord, String> APPNAME = createField(DSL.name("appname"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.overallappresults_import.endtime</code>.
     */
    public final TableField<OverallappresultsImportRecord, Double> ENDTIME = createField(DSL.name("endtime"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column
     * <code>public.overallappresults_import.iotdevicebatteryconsumption</code>.
     */
    public final TableField<OverallappresultsImportRecord, Double> IOTDEVICEBATTERYCONSUMPTION = createField(DSL.name("iotdevicebatteryconsumption"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>public.overallappresults_import.iotdevicedrained</code>.
     */
    public final TableField<OverallappresultsImportRecord, String> IOTDEVICEDRAINED = createField(DSL.name("iotdevicedrained"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.overallappresults_import.simulationtime</code>.
     */
    public final TableField<OverallappresultsImportRecord, Double> SIMULATIONTIME = createField(DSL.name("simulationtime"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>public.overallappresults_import.starttime</code>.
     */
    public final TableField<OverallappresultsImportRecord, Double> STARTTIME = createField(DSL.name("starttime"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column
     * <code>public.overallappresults_import.totalcloudletsizes</code>.
     */
    public final TableField<OverallappresultsImportRecord, Integer> TOTALCLOUDLETSIZES = createField(DSL.name("totalcloudletsizes"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column
     * <code>public.overallappresults_import.totaledgeletsizes</code>.
     */
    public final TableField<OverallappresultsImportRecord, Integer> TOTALEDGELETSIZES = createField(DSL.name("totaledgeletsizes"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column
     * <code>public.overallappresults_import.totaliotgenerateddata</code>.
     */
    public final TableField<OverallappresultsImportRecord, Integer> TOTALIOTGENERATEDDATA = createField(DSL.name("totaliotgenerateddata"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column
     * <code>public.overallappresults_import.totalmelgenerateddata</code>.
     */
    public final TableField<OverallappresultsImportRecord, Integer> TOTALMELGENERATEDDATA = createField(DSL.name("totalmelgenerateddata"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column
     * <code>public.overallappresults_import.apptotalrunningtime</code>.
     */
    public final TableField<OverallappresultsImportRecord, Double> APPTOTALRUNNINGTIME = createField(DSL.name("apptotalrunningtime"), SQLDataType.DOUBLE.nullable(false), this, "");

    private OverallappresultsImport(Name alias, Table<OverallappresultsImportRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private OverallappresultsImport(Name alias, Table<OverallappresultsImportRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.overallappresults_import</code> table
     * reference
     */
    public OverallappresultsImport(String alias) {
        this(DSL.name(alias), OVERALLAPPRESULTS_IMPORT);
    }

    /**
     * Create an aliased <code>public.overallappresults_import</code> table
     * reference
     */
    public OverallappresultsImport(Name alias) {
        this(alias, OVERALLAPPRESULTS_IMPORT);
    }

    /**
     * Create a <code>public.overallappresults_import</code> table reference
     */
    public OverallappresultsImport() {
        this(DSL.name("overallappresults_import"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public OverallappresultsImport as(String alias) {
        return new OverallappresultsImport(DSL.name(alias), this);
    }

    @Override
    public OverallappresultsImport as(Name alias) {
        return new OverallappresultsImport(alias, this);
    }

    @Override
    public OverallappresultsImport as(Table<?> alias) {
        return new OverallappresultsImport(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public OverallappresultsImport rename(String name) {
        return new OverallappresultsImport(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public OverallappresultsImport rename(Name name) {
        return new OverallappresultsImport(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public OverallappresultsImport rename(Table<?> name) {
        return new OverallappresultsImport(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OverallappresultsImport where(Condition condition) {
        return new OverallappresultsImport(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OverallappresultsImport where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OverallappresultsImport where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OverallappresultsImport where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OverallappresultsImport where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OverallappresultsImport where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OverallappresultsImport where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OverallappresultsImport where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OverallappresultsImport whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OverallappresultsImport whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
