/*
 * This file is generated by jOOQ.
 */
package uk.ncl.giacomobergami.utils.database.jooq.tables;


import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import uk.ncl.giacomobergami.utils.database.jooq.Public;
import uk.ncl.giacomobergami.utils.database.jooq.tables.records.PowerutilisationhistoryImportRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PowerutilisationhistoryImport extends TableImpl<PowerutilisationhistoryImportRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of
     * <code>public.powerutilisationhistory_import</code>
     */
    public static final PowerutilisationhistoryImport POWERUTILISATIONHISTORY_IMPORT = new PowerutilisationhistoryImport();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PowerutilisationhistoryImportRecord> getRecordType() {
        return PowerutilisationhistoryImportRecord.class;
    }

    /**
     * The column <code>public.powerutilisationhistory_import.dcname</code>.
     */
    public final TableField<PowerutilisationhistoryImportRecord, String> DCNAME = createField(DSL.name("dcname"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.powerutilisationhistory_import.puh_name</code>.
     */
    public final TableField<PowerutilisationhistoryImportRecord, String> PUH_NAME = createField(DSL.name("puh_name"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.powerutilisationhistory_import.starttime</code>.
     */
    public final TableField<PowerutilisationhistoryImportRecord, Double> STARTTIME = createField(DSL.name("starttime"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>public.powerutilisationhistory_import.usedmips</code>.
     */
    public final TableField<PowerutilisationhistoryImportRecord, Double> USEDMIPS = createField(DSL.name("usedmips"), SQLDataType.DOUBLE.nullable(false), this, "");

    private PowerutilisationhistoryImport(Name alias, Table<PowerutilisationhistoryImportRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private PowerutilisationhistoryImport(Name alias, Table<PowerutilisationhistoryImportRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.powerutilisationhistory_import</code>
     * table reference
     */
    public PowerutilisationhistoryImport(String alias) {
        this(DSL.name(alias), POWERUTILISATIONHISTORY_IMPORT);
    }

    /**
     * Create an aliased <code>public.powerutilisationhistory_import</code>
     * table reference
     */
    public PowerutilisationhistoryImport(Name alias) {
        this(alias, POWERUTILISATIONHISTORY_IMPORT);
    }

    /**
     * Create a <code>public.powerutilisationhistory_import</code> table
     * reference
     */
    public PowerutilisationhistoryImport() {
        this(DSL.name("powerutilisationhistory_import"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public PowerutilisationhistoryImport as(String alias) {
        return new PowerutilisationhistoryImport(DSL.name(alias), this);
    }

    @Override
    public PowerutilisationhistoryImport as(Name alias) {
        return new PowerutilisationhistoryImport(alias, this);
    }

    @Override
    public PowerutilisationhistoryImport as(Table<?> alias) {
        return new PowerutilisationhistoryImport(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public PowerutilisationhistoryImport rename(String name) {
        return new PowerutilisationhistoryImport(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PowerutilisationhistoryImport rename(Name name) {
        return new PowerutilisationhistoryImport(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public PowerutilisationhistoryImport rename(Table<?> name) {
        return new PowerutilisationhistoryImport(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PowerutilisationhistoryImport where(Condition condition) {
        return new PowerutilisationhistoryImport(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PowerutilisationhistoryImport where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PowerutilisationhistoryImport where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PowerutilisationhistoryImport where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PowerutilisationhistoryImport where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PowerutilisationhistoryImport where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PowerutilisationhistoryImport where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PowerutilisationhistoryImport where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PowerutilisationhistoryImport whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PowerutilisationhistoryImport whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
