/*
 * This file is generated by jOOQ.
 */
package uk.ncl.giacomobergami.utils.database.jooq.tables;


import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import uk.ncl.giacomobergami.utils.database.jooq.Public;
import uk.ncl.giacomobergami.utils.database.jooq.tables.records.RsuinformationImportRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RsuinformationImport extends TableImpl<RsuinformationImportRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.rsuinformation_import</code>
     */
    public static final RsuinformationImport RSUINFORMATION_IMPORT = new RsuinformationImport();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RsuinformationImportRecord> getRecordType() {
        return RsuinformationImportRecord.class;
    }

    /**
     * The column <code>public.rsuinformation_import.x</code>.
     */
    public final TableField<RsuinformationImportRecord, Double> X = createField(DSL.name("x"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>public.rsuinformation_import.y</code>.
     */
    public final TableField<RsuinformationImportRecord, Double> Y = createField(DSL.name("y"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>public.rsuinformation_import.simtime</code>.
     */
    public final TableField<RsuinformationImportRecord, Double> SIMTIME = createField(DSL.name("simtime"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column
     * <code>public.rsuinformation_import.communication_radius</code>.
     */
    public final TableField<RsuinformationImportRecord, Double> COMMUNICATION_RADIUS = createField(DSL.name("communication_radius"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column
     * <code>public.rsuinformation_import.max_vehicle_communication</code>.
     */
    public final TableField<RsuinformationImportRecord, Double> MAX_VEHICLE_COMMUNICATION = createField(DSL.name("max_vehicle_communication"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>public.rsuinformation_import.rsu_id</code>.
     */
    public final TableField<RsuinformationImportRecord, String> RSU_ID = createField(DSL.name("rsu_id"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    private RsuinformationImport(Name alias, Table<RsuinformationImportRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private RsuinformationImport(Name alias, Table<RsuinformationImportRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.rsuinformation_import</code> table
     * reference
     */
    public RsuinformationImport(String alias) {
        this(DSL.name(alias), RSUINFORMATION_IMPORT);
    }

    /**
     * Create an aliased <code>public.rsuinformation_import</code> table
     * reference
     */
    public RsuinformationImport(Name alias) {
        this(alias, RSUINFORMATION_IMPORT);
    }

    /**
     * Create a <code>public.rsuinformation_import</code> table reference
     */
    public RsuinformationImport() {
        this(DSL.name("rsuinformation_import"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public RsuinformationImport as(String alias) {
        return new RsuinformationImport(DSL.name(alias), this);
    }

    @Override
    public RsuinformationImport as(Name alias) {
        return new RsuinformationImport(alias, this);
    }

    @Override
    public RsuinformationImport as(Table<?> alias) {
        return new RsuinformationImport(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public RsuinformationImport rename(String name) {
        return new RsuinformationImport(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public RsuinformationImport rename(Name name) {
        return new RsuinformationImport(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public RsuinformationImport rename(Table<?> name) {
        return new RsuinformationImport(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RsuinformationImport where(Condition condition) {
        return new RsuinformationImport(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RsuinformationImport where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RsuinformationImport where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RsuinformationImport where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RsuinformationImport where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RsuinformationImport where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RsuinformationImport where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RsuinformationImport where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RsuinformationImport whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RsuinformationImport whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
