/*
 * This file is generated by jOOQ.
 */
package uk.ncl.giacomobergami.utils.database.jooq.tables;


import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import uk.ncl.giacomobergami.utils.database.jooq.Keys;
import uk.ncl.giacomobergami.utils.database.jooq.Public;
import uk.ncl.giacomobergami.utils.database.jooq.tables.records.SourcetodestlinksRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Sourcetodestlinks extends TableImpl<SourcetodestlinksRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.sourcetodestlinks</code>
     */
    public static final Sourcetodestlinks SOURCETODESTLINKS = new Sourcetodestlinks();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SourcetodestlinksRecord> getRecordType() {
        return SourcetodestlinksRecord.class;
    }

    /**
     * The column <code>public.sourcetodestlinks.unique_entry_id</code>.
     */
    public final TableField<SourcetodestlinksRecord, Integer> UNIQUE_ENTRY_ID = createField(DSL.name("unique_entry_id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.sourcetodestlinks.topology_id</code>.
     */
    public final TableField<SourcetodestlinksRecord, Integer> TOPOLOGY_ID = createField(DSL.name("topology_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.sourcetodestlinks.link_id</code>.
     */
    public final TableField<SourcetodestlinksRecord, Integer> LINK_ID = createField(DSL.name("link_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.sourcetodestlinks.from_id</code>.
     */
    public final TableField<SourcetodestlinksRecord, Integer> FROM_ID = createField(DSL.name("from_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.sourcetodestlinks.to_id</code>.
     */
    public final TableField<SourcetodestlinksRecord, Integer> TO_ID = createField(DSL.name("to_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.sourcetodestlinks.bw</code>.
     */
    public final TableField<SourcetodestlinksRecord, Double> BW = createField(DSL.name("bw"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>public.sourcetodestlinks.nochannels</code>.
     */
    public final TableField<SourcetodestlinksRecord, Integer> NOCHANNELS = createField(DSL.name("nochannels"), SQLDataType.INTEGER.nullable(false), this, "");

    private Sourcetodestlinks(Name alias, Table<SourcetodestlinksRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Sourcetodestlinks(Name alias, Table<SourcetodestlinksRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.sourcetodestlinks</code> table reference
     */
    public Sourcetodestlinks(String alias) {
        this(DSL.name(alias), SOURCETODESTLINKS);
    }

    /**
     * Create an aliased <code>public.sourcetodestlinks</code> table reference
     */
    public Sourcetodestlinks(Name alias) {
        this(alias, SOURCETODESTLINKS);
    }

    /**
     * Create a <code>public.sourcetodestlinks</code> table reference
     */
    public Sourcetodestlinks() {
        this(DSL.name("sourcetodestlinks"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<SourcetodestlinksRecord, Integer> getIdentity() {
        return (Identity<SourcetodestlinksRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<SourcetodestlinksRecord> getPrimaryKey() {
        return Keys.SOURCETODESTLINKS_PKEY;
    }

    @Override
    public Sourcetodestlinks as(String alias) {
        return new Sourcetodestlinks(DSL.name(alias), this);
    }

    @Override
    public Sourcetodestlinks as(Name alias) {
        return new Sourcetodestlinks(alias, this);
    }

    @Override
    public Sourcetodestlinks as(Table<?> alias) {
        return new Sourcetodestlinks(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Sourcetodestlinks rename(String name) {
        return new Sourcetodestlinks(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Sourcetodestlinks rename(Name name) {
        return new Sourcetodestlinks(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Sourcetodestlinks rename(Table<?> name) {
        return new Sourcetodestlinks(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Sourcetodestlinks where(Condition condition) {
        return new Sourcetodestlinks(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Sourcetodestlinks where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Sourcetodestlinks where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Sourcetodestlinks where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Sourcetodestlinks where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Sourcetodestlinks where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Sourcetodestlinks where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Sourcetodestlinks where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Sourcetodestlinks whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Sourcetodestlinks whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
