/*
 * This file is generated by jOOQ.
 */
package uk.ncl.giacomobergami.utils.database.jooq.tables;


import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import uk.ncl.giacomobergami.utils.database.jooq.Public;
import uk.ncl.giacomobergami.utils.database.jooq.tables.records.SwitchpowerconsumptionImportRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SwitchpowerconsumptionImport extends TableImpl<SwitchpowerconsumptionImportRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of
     * <code>public.switchpowerconsumption_import</code>
     */
    public static final SwitchpowerconsumptionImport SWITCHPOWERCONSUMPTION_IMPORT = new SwitchpowerconsumptionImport();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SwitchpowerconsumptionImportRecord> getRecordType() {
        return SwitchpowerconsumptionImportRecord.class;
    }

    /**
     * The column <code>public.switchpowerconsumption_import.dcname</code>.
     */
    public final TableField<SwitchpowerconsumptionImportRecord, String> DCNAME = createField(DSL.name("dcname"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.switchpowerconsumption_import.energy</code>.
     */
    public final TableField<SwitchpowerconsumptionImportRecord, Double> ENERGY = createField(DSL.name("energy"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>public.switchpowerconsumption_import.spc_name</code>.
     */
    public final TableField<SwitchpowerconsumptionImportRecord, String> SPC_NAME = createField(DSL.name("spc_name"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    private SwitchpowerconsumptionImport(Name alias, Table<SwitchpowerconsumptionImportRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private SwitchpowerconsumptionImport(Name alias, Table<SwitchpowerconsumptionImportRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.switchpowerconsumption_import</code> table
     * reference
     */
    public SwitchpowerconsumptionImport(String alias) {
        this(DSL.name(alias), SWITCHPOWERCONSUMPTION_IMPORT);
    }

    /**
     * Create an aliased <code>public.switchpowerconsumption_import</code> table
     * reference
     */
    public SwitchpowerconsumptionImport(Name alias) {
        this(alias, SWITCHPOWERCONSUMPTION_IMPORT);
    }

    /**
     * Create a <code>public.switchpowerconsumption_import</code> table
     * reference
     */
    public SwitchpowerconsumptionImport() {
        this(DSL.name("switchpowerconsumption_import"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public SwitchpowerconsumptionImport as(String alias) {
        return new SwitchpowerconsumptionImport(DSL.name(alias), this);
    }

    @Override
    public SwitchpowerconsumptionImport as(Name alias) {
        return new SwitchpowerconsumptionImport(alias, this);
    }

    @Override
    public SwitchpowerconsumptionImport as(Table<?> alias) {
        return new SwitchpowerconsumptionImport(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public SwitchpowerconsumptionImport rename(String name) {
        return new SwitchpowerconsumptionImport(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SwitchpowerconsumptionImport rename(Name name) {
        return new SwitchpowerconsumptionImport(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public SwitchpowerconsumptionImport rename(Table<?> name) {
        return new SwitchpowerconsumptionImport(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SwitchpowerconsumptionImport where(Condition condition) {
        return new SwitchpowerconsumptionImport(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SwitchpowerconsumptionImport where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SwitchpowerconsumptionImport where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SwitchpowerconsumptionImport where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SwitchpowerconsumptionImport where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SwitchpowerconsumptionImport where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SwitchpowerconsumptionImport where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SwitchpowerconsumptionImport where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SwitchpowerconsumptionImport whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SwitchpowerconsumptionImport whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
